#+TITLE: scratchpad

* Mathematica

#+NAME: example-table
  | 1 | 4 |
  | 2 | 4 |
  | 3 | 6 |
  | 4 | 8 |
  | 7 | 0 |

#+BEGIN_SRC mathematica :var x=example-table :results raw
  (1+Transpose@x) // TeXForm
#+END_SRC

#+RESULTS:
\left(
\begin{array}{ccccc}
 2 & 3 & 4 & 5 & 8 \\
 5 & 5 & 7 & 9 & 1 \\
\end{array}
\right)

* R Notebook

#+BEGIN_SRC R :results output org
library(ascii)
options(asciiType = "org")
ascii(summary(ToothGrowth))
#+END_SRC

#+RESULTS:
#+begin_src org
|   | len           | supp  | dose          |
|---+---------------+-------+---------------|
| 1 | Min.   : 4.20 | OJ:30 | Min.   :0.500 |
| 2 | 1st Qu.:13.07 | VC:30 | 1st Qu.:0.500 |
| 3 | Median :19.25 |       | Median :1.000 |
| 4 | Mean   :18.81 |       | Mean   :1.167 |
| 5 | 3rd Qu.:25.27 |       | 3rd Qu.:2.000 |
| 6 | Max.   :33.90 |       | Max.   :2.000 |
#+end_src

#+BEGIN_SRC R :exports results :results output
Hmisc::describe(ToothGrowth)
#+END_SRC

#+RESULTS:
#+begin_example
ToothGrowth

 3  Variables      60  Observations
----------------------------------------------------------------------------------------------------
len
       n  missing distinct     Info     Mean      Gmd      .05      .10      .25      .50      .75
      60        0       43    0.999    18.81    8.839     6.37     8.11    13.07    19.25    25.27
     .90      .95
   27.30    29.57

lowest :  4.2  5.2  5.8  6.4  7.0, highest: 29.4 29.5 30.9 32.5 33.9
----------------------------------------------------------------------------------------------------
supp
       n  missing distinct
      60        0        2

Value       OJ  VC
Frequency   30  30
Proportion 0.5 0.5
----------------------------------------------------------------------------------------------------
dose
       n  missing distinct     Info     Mean      Gmd
      60        0        3    0.889    1.167    0.678

Value        0.5   1.0   2.0
Frequency     20    20    20
Proportion 0.333 0.333 0.333
----------------------------------------------------------------------------------------------------
#+end_example

#+BEGIN_SRC R :results output
library(dplyr)
options(width = 100)
ToothGrowth %>%
  group_by(supp) %>%
  skimr::skim()
#+END_SRC

#+RESULTS:
#+begin_example
── Data Summary ────────────────────────
                           Values
Name                       Piped data
Number of rows             60
Number of columns          3
_______________________
Column type frequency:
  numeric                  2
________________________
Group variables            supp

── Variable type: numeric ──────────────────────────────────────────────────────────────────────────
  skim_variable supp  n_missing complete_rate  mean    sd    p0   p25   p50   p75  p100 hist
1 len           OJ            0             1 20.7  6.61    8.2  15.5  22.7  25.7  30.9 ▅▃▅▇▆
2 len           VC            0             1 17.0  8.27    4.2  11.2  16.5  23.1  33.9 ▇▇▇▇▃
3 dose          OJ            0             1  1.17 0.634   0.5   0.5   1     2     2   ▇▇▁▁▇
4 dose          VC            0             1  1.17 0.634   0.5   0.5   1     2     2   ▇▇▁▁▇
#+end_example

#+BEGIN_SRC R :results output html
library(tidyverse)
library(gt)
ToothGrowth %>%
  filter(supp == "OJ") %>%
  mutate(dose = factor(dose, ordered = TRUE)) %>%
  group_by(dose) %>%
  summarize(mean = mean(len)) %>%
  gt()
#+END_SRC

* Lisp Notebook

#+BEGIN_SRC emacs-lisp
(+ 1 3)
#+END_SRC


* Python Notebook

#+BEGIN_SRC python :results output
key = "Babel"
print("Hello %s" % (key))
#+END_SRC

From [[https://programmingpraxis.com/2018/04/13/third-biggest-number/][Programming Praxis]].

Originally, the task is to "Write a program to read ten numbers input by the user and write the third largest of those ten numbers." I choose to replace user input with random integers.

This amounts to draw a reandom sequence of 10 values, sort them in descending order and select the 3rd value. We can safely ignore any ties in the list. With Python 3.6, it would be interesting to try the [[https://docs.python.org/3.6/library/secrets.html#module-secrets][secrets]] module.

#+BEGIN_SRC python :results output
from random import seed, randint
seed(101)
x = sorted([randint(1, 10) for i in range(0, 9)], reverse=True)
print("Answer = value %s in sequence %s" % (x[2], x))
#+END_SRC

Now, in Clojure:

#+BEGIN_SRC clojure
(def x (sort > (take 10 (repeatedly #(rand-int 10)))))
(let [[a b c] x]
    (println x)
    (println c))
#+END_SRC

This does not allow to fix the seed while keeping the laziness (see [[https://kotka.de/blog/2009/11/Taming_the_Bound_Seq.html][Taming the Bound Seq]]). Here is an [[https://stackoverflow.com/a/22460517][alternative solution]] from Stack Overflow:

#+BEGIN_SRC clojure
(ns example.show
  (:require [clojure.data.generators :as g]))

(defn rand-seq [seed]
  (let [r (java.util.Random. seed)]
    (repeatedly #(binding [g/*rnd* r]
                   (inc (g/uniform 0 10))))))

(take 10 (rand-seq 42))
#+END_SRC

It is weird that we cannot set the seed of PRNGs unless we use ~data.generators~. In CL, we have ~random-state~.
See [[https://dcatteeu.github.io/article/2014/07/31/random-numbers/][Random Numbers in Common Lisp]].
