
* Bookmarks to file
** How to use matrix.org and vector.im as an IRC client
[2020-06-16 Tue 11:19]
https://gist.github.com/fstab/ce805d3001600ac147b79d413668770d
** Guide to Matrix.org and Riot.im
[2020-06-16 Tue 11:20]
https://dzone.com/articles/guide-to-matrixorg-and-riotim
** Failed to change nick: err_unavailresource after Riot upgrade #828
[2020-06-16 Tue 11:21]
https://github.com/matrix-org/matrix-appservice-irc/issues/828
** matrix-client.el
[2020-06-16 Tue 11:22]
https://github.com/alphapapa/matrix-client.el/blob/master/README.org
** Matrix IRCd
[2020-06-16 Tue 11:22]
https://github.com/matrix-org/matrix-ircd/blob/master/README.md
** Guide: How to use Matrix to participate in IRC rooms
[2020-06-16 Tue 11:24]
https://github.com/matrix-org/matrix-appservice-irc/wiki/Guide:-How-to-use-Matrix-to-participate-in-IRC-rooms
** unsafeClient not ready yet error #944
[2020-06-16 Tue 11:24]
https://github.com/matrix-org/matrix-appservice-irc/issues/944
** Discord bridge
[2020-06-16 Tue 11:25]
https://t2bot.io/discord/
** How to bridge Freenode IRC rooms to Matrix.org
[2020-06-16 Tue 11:25]
https://archive.org/details/hpr3034
** A bridge between Matrix and Discord
[2020-06-16 Tue 11:25]
https://github.com/Half-Shot/matrix-appservice-discord
** IRC and IRC Bouncer
[2020-06-16 Tue 11:26]
https://championshuttler.wordpress.com/2017/11/23/irc-and-irc-bouncer/
** Is there a benefit to using ZNC on my VPS or just having weechat running on it all the time?
[2020-06-16 Tue 11:27]
https://www.reddit.com/r/irc/comments/5imdjv/is_there_a_benefit_to_using_znc_on_my_vps_or_just/
** IRC Reference
[2020-06-16 Tue 11:38]
https://gist.github.com/xero/2d6e4b061b4ecbeb9f99
** private DOOM emacs configuration
[2020-06-16 Tue 11:40]
https://github.com/nmartin84/.doom.d
** Ubuntu / OS X dotfiles using at Dwarves Foundation
[2020-06-16 Tue 11:41]
https://github.com/dwarvesf/dotfiles
** tmux cheatsheet
[2020-06-16 Tue 11:44]
https://gist.github.com/henrik/1967800
** Add Webmention Support
[2020-06-16 Tue 20:32]
https://kevin.thecorams.net/site/2019/12/add-webmention-support/
** Hugo
[2020-06-16 Tue 20:33]
https://indieweb.org/Hugo
**
[2020-06-16 Tue 20:33]
https://indieweb.org/Hugo
** Implementing Webmention on a static website
[2020-06-16 Tue 20:33]
https://deluvi.com/blog/webmention/
** Emacs init file for Mike Hamrick
[2020-06-16 Tue 20:36]
https://gitlab.com/spudlyo/dotfiles/-/blob/master/emacs/.emacs.d/init.el
** Various coding repos                                                       :misc:
[2020-06-16 Tue 20:38]
https://bitbucket.org/bos/
** Eamonn Sullivan's emacs config
[2020-06-16 Tue 20:39]
https://github.com/eamonnsullivan/emacs.d
** Mac OS X tmux config
[2020-06-16 Tue 20:39]
https://gist.github.com/jrgcubano/fdcf3a903f56b1af4dca
** Alain M. Lafon's emacs config
[2020-06-16 Tue 20:40]
https://github.com/munen/emacs.d/blob/master/configuration.org

* Safari reading list
** Statistics for laboratory scientists II
[2020-06-27 Sat 20:21]
https://www.biostat.wisc.edu/~kbroman/teaching/labstat/fourth/
** Data wrangling, exploration, and analysis with R
[2020-06-27 Sat 20:22]
https://stat545.com/
** Explained Visually
[2020-06-27 Sat 20:23]
https://setosa.io/ev/
** Data Mining: Spring 2013
[2020-06-27 Sat 20:24]
http://www.stat.cmu.edu/~ryantibs/datamining/
** Mining of Massive Datasets
[2020-06-27 Sat 20:24]
http://www.mmds.org/
** Support de cours DATA MINING et DATA SCIENCE
[2020-06-27 Sat 20:24]
http://eric.univ-lyon2.fr/~ricco/cours/supports_data_mining.html
** Arcene Data Set
[2020-06-27 Sat 20:27]
https://archive.ics.uci.edu/ml/datasets/Arcene
** STAT 545 by Rao
[2020-06-27 Sat 20:28]
https://www.stat.purdue.edu/~varao/STAT545/main.html
** General Statistical Ideas
[2020-06-27 Sat 20:28]
http://biostat.mc.vanderbilt.edu/wiki/Main/ClinStat
** STAT 133
[2020-06-27 Sat 20:29]
http://www.gastonsanchez.com/stat133/lectures/
** Practical Machine Learning Tools and Techniques
[2020-06-27 Sat 20:31]
https://www.cs.waikato.ac.nz/ml/weka/book.html
** Foundations of Data Science — Spring 2016
[2020-06-27 Sat 20:31]
https://data-8.appspot.com/sp16/course
** Reactive Vega
[2020-06-27 Sat 20:32]
http://idl.cs.washington.edu/papers/reactive-vega-architecture/
** The Lyra Visualization Design Environment
[2020-06-27 Sat 20:32]
http://idl.cs.washington.edu/projects/lyra/
** R for Data Science
[2020-06-27 Sat 20:33]
https://r4ds.had.co.nz/
** Fundamentals of Data Analysis and Visualization                            :stata:
[2020-06-27 Sat 20:34]
http://geocenter.github.io/StataTraining/about/
** Vega & Vega-Lite
[2020-06-27 Sat 20:34]
https://vega.github.io/
** Statistical Modeling with Stata
[2020-06-27 Sat 20:35]
http://personalpages.manchester.ac.uk/staff/mark.lunt/stats_course.html
** Exploring Histograms
[2020-06-27 Sat 20:35]
https://www.informationisbeautifulawards.com/showcase/2553
** The datasaurus
[2020-06-27 Sat 20:35]
https://www.autodeskresearch.com/publications/samestats
** Idyll
[2020-06-27 Sat 20:36]
https://idyll-lang.org/
** Michael Freeman
[2020-06-27 Sat 20:36]
http://mfviz.com/
** Most interactive textbooks are crap
[2020-06-27 Sat 20:37]
https://www.refsmmat.com/notebooks/textbooks.html
** Reading for Programmers
[2020-06-27 Sat 20:38]
https://codearsonist.com/reading-for-programmers
** Easy Lecture Slides Made Difficult with Pandoc and Beamer
[2020-06-27 Sat 20:39]
https://andrewgoldstone.com/blog/2014/12/24/slides/
** Exploring a Data Set in SQL
[2020-06-27 Sat 20:40]
https://tapoueh.org/blog/2017/06/exploring-a-data-set-in-sql/
** Generalized Linear Models                                                  :stata:
[2020-06-27 Sat 20:41]
https://data.princeton.edu/wws509
** Hugo Bowne-Anderson
[2020-06-27 Sat 20:42]
http://hugobowne.github.io/
** necessary-disorder tutorials
[2020-06-27 Sat 20:42]
https://necessarydisorder.wordpress.com/
** Robust Statistics using Stata
[2020-06-27 Sat 20:43]
https://www.stata.com/meeting/belgium16/slides/belgium16_verardi.pdf
** Robust Statistics in Stata (2017)
[2020-06-27 Sat 20:43]
https://www.stata.com/meeting/uk17/slides/uk17_Jann2.pdf
** Machine Learning and Econometrics
[2020-06-27 Sat 20:44]
https://web.stanford.edu/class/ee380/Abstracts/140129-slides-Machine-Learning-and-Econometrics.pdf
** NBER Lectures on Machine Learning
[2020-06-27 Sat 20:44]
http://www.nber.org/econometrics_minicourse_2015/nber_slides11.pdf
** Machine Learning for Microeconometrics
[2020-06-27 Sat 20:44]
http://cameron.econ.ucdavis.edu/e240f/trmachinelearningseminar.pdf
** ldagibbs: A command for Topic Modeling in Stata                            :stata:
[2020-06-27 Sat 20:45]
https://warwick.ac.uk/fac/soc/economics/staff/crschwarz/lda_stata.pdf
** Coding with Mata in Stata
[2020-06-27 Sat 20:45]
https://www.schmidheiny.name/teaching/statamata.pdf
** Mata Programming I
[2020-06-27 Sat 20:46]
http://www.ncer.edu.au/events/documents/QUT15S2.slides.pdf
** Simple data processing with Haskell
[2020-06-27 Sat 20:47]
https://medium.com/the-theam-journey/simple-data-processing-with-haskell-b79cea4d0a2d
** Oliver Kirchkamp
[2020-06-27 Sat 20:47]
https://www.kirchkamp.de/teaching-grad.html
** Why is Difference-in-Difference Estimation Still so Popular in Experimental Analysis?
[2020-06-27 Sat 20:48]
https://blogs.worldbank.org/impactevaluations/why-difference-difference-estimation-still-so-popular-experimental-analysis
** A Visual Guide to Version Control
[2020-06-27 Sat 20:48]
https://betterexplained.com/articles/a-visual-guide-to-version-control/
** Mac keyboard shortcuts
[2020-06-27 Sat 20:48]
https://support.apple.com/en-us/HT201236
** Productizing Data Science at Twitch
[2020-06-27 Sat 20:49]
https://blog.twitch.tv/en/2017/06/01/productizing-data-science-at-twitch-67a643fd8c44/
** Emacs org-mode examples and cookbook
[2020-06-27 Sat 20:52]
http://ehneilsen.net/notebook/orgExamples/org-examples.html
** The Hacker Ways
[2020-06-27 Sat 20:52]
https://github.com/juanre/hacker-ways
** Blogging using org-mode (and nothing else)
[2020-06-27 Sat 20:53]
https://ogbe.net/blog/blogging_with_org.html
** Stata and R Markdown
[2020-06-27 Sat 20:54]
https://www.ssc.wisc.edu/~hemken/Stataworkshops/Stata%20and%20R%20Markdown/
** Where can I find some rich book classes?
[2020-06-27 Sat 20:55]
https://tex.stackexchange.com/questions/134215/where-can-i-find-some-rich-book-classes
** A birds-eye view of optimization algorithms
[2020-06-27 Sat 20:55]
http://fa.bianp.net/pages/teaching.html
** STAT 501 | Regression Methods
[2020-06-27 Sat 20:56]
https://online.stat.psu.edu/stat501/node/353
** Category Theory with Applications in Functional Programming
[2020-06-27 Sat 20:56]
http://www.lix.polytechnique.fr/Labo/Ulrich.Fahrenberg/Teaching/09/Fall/CatFunc/
** Definitions with a Crossover Design
[2020-06-27 Sat 20:56]
https://online.stat.psu.edu/stat509/node/126/
** Biostatistics: ANOVA and Design
[2020-06-27 Sat 20:57]
http://www.biostat.umn.edu/~lynn/ph7406.html
** Making Data Visual
[2020-06-27 Sat 20:58]
https://makingdatavisual.github.io/
** Beaker Browser
[2020-06-27 Sat 21:00]
https://beakerbrowser.com/
** Comprehensive data exploration with python
[2020-06-27 Sat 21:00]
https://www.kaggle.com/pmarcelino/comprehensive-data-exploration-with-python
** Stata and Literate Programming in Emacs Org-Mode
[2020-06-27 Sat 21:01]
https://rlhick.people.wm.edu/posts/stata-and-literate-programming-in-emacs-org-mode.html
** Pretty Magit - Integrating commit leaders
[2020-06-27 Sat 21:01]
http://www.modernemacs.com/post/pretty-magit/
** Working with Git from Emacs
[2020-06-27 Sat 21:02]
http://alexott.net/en/writings/emacs-vcs/EmacsGit.html
** Read Random Rows from A Huge CSV File
[2020-06-27 Sat 21:02]
https://statcompute.wordpress.com/2018/04/
** Reverse engineering stickies.app
[2020-06-27 Sat 21:03]
https://lowlevelbits.org/reverse-engineering-stickies.app/
** doom-emacs-private-xfu
[2020-06-27 Sat 21:04]
https://github.com/fuxialexander/doom-emacs-private-xfu
** Ned Batchelder
[2020-06-27 Sat 21:04]
https://nedbatchelder.com/
** How I got started with Common Lisp in 2017
[2020-06-27 Sat 21:04]
https://www.reddit.com/r/lisp/comments/6y3db8/how_i_got_started_with_common_lisp_in_2017/
** How to Design Programs
[2020-06-27 Sat 21:06]
https://htdp.org/2018-01-06/Book/
** Combinatorial Generation Using Coroutines With Examples in Python
[2020-06-27 Sat 21:06]
https://sahandsaba.com/combinatorial-generation-using-coroutines-in-python.html#knuth-4a
** William Kahan
[2020-06-27 Sat 21:07]
https://people.eecs.berkeley.edu/~wkahan/
** The Ultimate Vim Distribution
[2020-06-27 Sat 21:07]
http://vim.spf13.com/
** Export Settings
[2020-06-27 Sat 21:07]
https://orgmode.org/manual/Export-Settings.html#Export-settings
** Stata commands
[2020-06-27 Sat 21:08]
http://staskolenikov.net/stata/Duke/commands.html
** Jeff Stafford
[2020-06-27 Sat 21:08]
https://jstaf.github.io/teaching/
** Introduction to Machine Learning for Coders: Launch
[2020-06-28 Sun 08:05]
https://www.fast.ai/2018/09/26/ml-launch/
** Flask 101: Adding, Editing and Displaying Data
[2020-06-28 Sun 08:05]
https://www.blog.pythonlibrary.org/2017/12/14/flask-101-adding-editing-and-displaying-data/
** Flask by Example – Text Processing with Requests, BeautifulSoup, and NLTK
[2020-06-28 Sun 08:05]
https://realpython.com/flask-by-example-part-3-text-processing-with-requests-beautifulsoup-nltk/
** Vagrant: Getting Started
[2020-06-28 Sun 08:06]
https://www.vagrantup.com/intro/getting-started
** Vim after 15 years
[2020-06-28 Sun 08:07]
https://statico.github.io/vim3.html
** Project Euler solutions by Nayuki
[2020-06-28 Sun 08:11]
https://www.nayuki.io/page/project-euler-solutions
** exercism (racket)
[2020-06-28 Sun 08:12]
https://github.com/exercism/racket/tree/master/exercises
** Access log data analysis
[2020-06-28 Sun 08:12]
https://blog.exploratory.io/access-log-data-analysis-part1-understanding-your-customer-interactions-adcfeef67d21
** Simple image vectorization
[2020-06-28 Sun 08:12]
https://wordsandbuttons.online/simple_image_vectorization.html
** Dealing with GenBank files in Biopython
[2020-06-28 Sun 08:13]
https://warwick.ac.uk/fac/sci/moac/people/students/peter_cock/python/genbank/
** phylogenetics module of Genome Sciences 541
[2020-06-28 Sun 08:13]
https://matsen.github.io/teaching/courses/GS541/
** Generating Fucntion Tutorial
[2020-06-28 Sun 08:13]
https://yuyuan.org/GeneratingFunctionTutorial/
** Publishing Org-mode files to HTML
[2020-06-28 Sun 08:14]
https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html
** Analyzing RNA-seq data with DESeq2
[2020-06-28 Sun 08:14]
https://www.bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html
** SAMtools: Primer / Tutorial
[2020-06-28 Sun 08:15]
http://biobits.org/samtools_primer.html
** RNA-Seq differential expression work flow using DESeq2
[2020-06-28 Sun 08:15]
http://www.sthda.com/english/wiki/rna-seq-differential-expression-work-flow-using-deseq2
** Short read analysis
[2020-06-28 Sun 08:15]
https://biodataprog.github.io/2018_programming-intro/Lectures/12_short_read_analysis.html#5
** Docker.raw reserving too much size #2297
[2020-06-28 Sun 08:16]
https://github.com/docker/for-mac/issues/2297
** More solutions to SPOJ programming problems
[2020-06-28 Sun 08:16]
https://blog.dreamshire.com/more-solutions-to-spoj-programming-problems/
** Introduction; Master Equation
[2020-06-28 Sun 08:16]
https://ocw.mit.edu/courses/physics/8-592j-statistical-physics-in-biology-spring-2011/lecture-notes/introduction/
** Computational Molecular Biology and Genomics Syllabus
[2020-06-28 Sun 08:17]
https://www.cs.cmu.edu/~durand/03-711/2015/
** Getting Started With Jekyll And GitHub Pages
[2020-06-28 Sun 08:17]
https://alexanderjdupree.github.io/blog/guide/tutorial/Getting-Started-With-Jekyll-And-GitHub-Pages/
** Teaching materials at the Harvard Chan Bioinformatics Core
[2020-06-28 Sun 08:17]
https://github.com/hbctraining
** Django CRUD App With SQLite
[2020-06-28 Sun 08:18]
https://github.com/piinalpin/django-crud-sqlite
** Generating random numbers in R and Racket
[2020-06-28 Sun 08:18]
https://www.travishinkelman.com/posts/generating-random-numbers-r-racket/
** Neil Toronto
[2020-06-28 Sun 08:27]
https://www.cs.umd.edu/~ntoronto/
** Andrew M. Kent
[2020-06-28 Sun 08:28]
https://pnwamk.github.io/
** Efficient and accurate rolling standard deviation
[2020-06-28 Sun 08:28]
https://jonisalonen.com/2014/efficient-and-accurate-rolling-standard-deviation/
** Tracing a Program As It Runs
[2020-06-28 Sun 08:28]
https://pymotw.com/2/sys/tracing.html
** Interface for Machine Learning Modeling, Testing and Training
[2020-06-28 Sun 08:29]
https://github.com/plandes/clj-ml-model
** Advanced Hackery With The Hammerspoon Window Manager
[2020-06-28 Sun 08:29]
https://thume.ca/2016/07/16/advanced-hackery-with-the-hammerspoon-window-manager/
** yabai: Tiling window management for the Mac
[2020-06-28 Sun 08:29]
https://github.com/koekeishiya/yabai
** What’s Wrong With Statistics in Julia? A Reply
[2020-06-28 Sun 08:30]
https://web.archive.org/web/20160527011008/http://wizardmac.tumblr.com/post/104019606584/whats-wrong-with-statistics-in-julia-a-reply
** Regexr
[2020-06-28 Sun 08:32]
https://regexr.com/
** Make a Discord Webhook
[2020-06-28 Sun 08:32]
https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22
** A cross-platform Discord music bot with a clean interface, and that is easy to set up and run yourself!
[2020-06-28 Sun 08:32]
https://github.com/jagrosh/MusicBot
** Introduction to Mathematical Statistics
[2020-06-28 Sun 08:32]
http://statweb.stanford.edu/~susan/courses/s200/
** A complete iTunes movie converter
[2020-06-28 Sun 08:33]
https://www.tuneskit.com/m4v-converter/?agency_id=8
** Darling is a translation layer that lets you run macOS software on Linux
[2020-06-28 Sun 08:33]
https://darlinghq.org/
** Continuation-passing style
[2020-06-28 Sun 08:34]
https://en.wikipedia.org/wiki/Continuation-passing_style
** Sage Gerard
[2020-06-28 Sun 08:34]
https://github.com/zyrolasting
** MATHEMATICA / Mathics tutorial
[2020-06-28 Sun 08:34]
http://www.cfm.brown.edu/people/dobrush/am33/Mathematica/
** rsapkf dotfiles
[2020-06-28 Sun 08:35]
https://github.com/rsapkf/dotfiles
** Rosalind sol in Python
[2020-06-28 Sun 08:35]
https://github.com/adelq/rosalind
** Rosaling sol in Python (bis)
[2020-06-28 Sun 08:36]
https://github.com/timothymahajan/Project-Rosalind-Bioinformatics-Stronghold
** Bayesian Econometrics Introduction
[2020-06-28 Sun 08:36]
https://rlhick.people.wm.edu/stories/bayesian_1.html
** Efficient computation of integer representation as a sum of three squares
[2020-06-28 Sun 08:37]
https://mathoverflow.net/questions/104322/efficient-computation-of-integer-representation-as-a-sum-of-three-squares
** Iterate sum of two squares                                                 :python:
[2020-06-28 Sun 09:04]
https://stackoverflow.com/questions/20119967/iterate-sum-of-two-squares
** Non-English characters in Stata
[2020-06-28 Sun 09:04]
https://sites.google.com/site/imirkina/cookbook-stata/non-western-characters-in-stata
** Stata Tutorial
[2020-06-28 Sun 09:04]
https://data.princeton.edu/stata
** Common lisp cancellation error floating point
[2020-06-28 Sun 09:05]
https://duckduckgo.com/?q=common+lisp+cancellation+error+floating+point&t=iphone&ia=qa
** CI/CD - Serverless Ebook using Gitbook CLI, Github Pages, Github Actions CI/CD, and Calibre
[2020-06-28 Sun 09:06]
https://devops.novalagung.com/en/cicd-serverless-ebook-gitbook-github-pages-actions-calibre.html
** Emacs Configuration
[2020-06-28 Sun 09:07]
https://emacs.christianbaeuerlein.com/
** doom-emacs-literate-config
[2020-06-28 Sun 09:07]
https://github.com/Brettm12345/doom-emacs-literate-config
** jethrokuan dot files
[2020-06-28 Sun 09:08]
https://github.com/jethrokuan/dots/blob/master/.doom.d/config.el
** Eli Zaretskii emacs files
[2020-06-28 Sun 09:09]
http://git.savannah.gnu.org/cgit/emacs.git/commit/etc/NEWS?id=7a7090029437ae7981d3bba9722bdc8f4695fed3
** Building a Machine Learning (ML) Model with PySpark
[2020-06-28 Sun 09:10]
https://towardsdatascience.com/first-time-machine-learning-model-with-pyspark-3684cf406f54
** Seeing Theory
[2020-06-28 Sun 09:11]
https://seeing-theory.brown.edu/
** Jacobi Theta functions #373
[2020-06-28 Sun 09:11]
https://github.com/boostorg/math/issues/373
