* Inbox
** A collection of graph classification methods
 [2020-04-12 Sun 21:02]
 https://github.com/benedekrozemberczki/awesome-graph-classification
** So You Want to Be a (Compiler) Wizard
 [2020-04-12 Sun 20:55]
 https://belkadan.com/blog/2016/05/So-You-Want-To-Be-A-Compiler-Wizard/
** Programming Language Theory
 [2020-04-12 Sun 20:50]
 https://steshaw.org/plt/
** Processing and Racket
 [2020-04-12 Sun 20:45]
 https://www.hive76.org/2013/06/01/processing-and-racket/
** Probabilistic programming in Racket
 [2020-04-12 Sun 20:44]
 http://rmculpepper.github.io/gamble/
** covdata package (interesting for ggplot)
 [2020-04-11 Sat 20:35]
 36:39: execution error: Erreur dans Safari : L’application n’est pas ouverte. (-600)
** SIR model in Python
 [2020-04-11 Sat 09:59]
 https://johnlekberg.com/blog/2020-04-10-cli-infection.html
** Clojure babushka                                                            :clojure:
 [2020-04-10 Fri 19:27]
 https://github.com/borkdude/babashka
** Great Looking Tables: gt                                                    :rstats:
 [2020-04-10 Fri 19:26]
 https://blog.rstudio.com/2020/04/08/great-looking-tables-gt-0-2/
** Time Series Forecasting Best Practices & Examples (Microsoft)               :statistics:
 [2020-04-10 Fri 19:25]
 https://github.com/microsoft/forecasting
** Today I learned (tip & tricks)                                              :misc:
 [2020-04-10 Fri 19:25]
 http://jonasbn.github.io/til/#itermapp
** Inspectra is a tool for spectral comparison of graph topology               :python:graphs:
 [2020-04-10 Fri 19:23]
 https://github.com/cancerregulome/inspectra
** Scheme in FORTH in Julia                                                    :julia:scheme:
 [2020-04-09 Thu 20:08]
 https://github.com/tgvaughan/scheme.forth.jl
** The Ten Rules for Data Modeling with DynamoDB                               :database:
 [2020-04-08 Wed 19:58]
 https://www.trek10.com/blog/the-ten-rules-for-data-modeling-with-dynamodb
** Using SIMD to aggregate billions of rows per second (on a laptop)           :database:
 [2020-04-08 Wed 08:02]
 https://www.questdb.io/blog/2020/04/02/using-simd-to-aggregate-billions-of-rows-per-second
** A humble guide to database schema design                                    :database:
 [2020-04-08 Wed 08:01]
 https://www.mikealche.com/software-development/a-humble-guide-to-database-schema-design
** Duo is a collection of colour combinations                                  :misc:
 [2020-04-07 Tue 17:23]
 https://duo.alexpate.uk/
** A general purpose community detection and network embedding library         :graphs:python:
 [2020-04-07 Tue 16:24]
 https://github.com/benedekrozemberczki/karatecluB
** Code for modelling estimated deaths and cases for COVID19                   :statistics:
 [2020-04-06 Mon 20:12]
 https://github.com/ImperialCollegeLondon/covid19model
** org-protocol-capture-html                                                   :org:
 [2020-04-06 Mon 17:33]
 https://github.com/alphapapa/org-protocol-capture-html
** Minecraft Harmony                                                           :misc:
 [2020-04-06 Mon 11:30]
 http://michaellynn.github.io/2020/03/28/minecraft-harmony/
** Flask app by karpathy on COVID-19                                           :python:
 [2020-04-06 Mon 11:29]
 https://github.com/karpathy/covid-sanity
** Template elements in Org                                                    :org:
 [2020-04-03 Fri 10:48]
 https://orgmode.org/manual/Template-elements.html#Template-elements
** Previewing LaTeX fragments                                                  :org:
 [2020-04-03 Fri 10:31]
 https://orgmode.org/manual/Previewing-LaTeX-fragments.html#Previewing-LaTeX-fragments
** Python-3-Cheatsheet                                                         :python:
 [2020-04-02 Thu 09:10]
 https://yungnickyoung.github.io/Python-3-Cheatsheet/
** Jami is free software for universal communication                           :misc:
 [2020-04-02 Thu 08:44]
 https://git.jami.net/savoirfairelinux/ring-project/wikis/home
** How to SSH Properly                                                         :misc:
 [2020-04-02 Thu 08:43]
 https://gravitational.com/blog/how-to-ssh-properly/
** An Overview of Bayesian Inference                                           :bayesian:
 [2020-04-01 Wed 21:24]
 https://jaydaigle.net/blog/overview-of-bayesian-inference/
** Restarts in Common Lisp                                                     :lisp:
 [2020-04-01 Wed 20:15]
 https://sulami.github.io/posts/common-lisp-restarts/
** How Dolt Stores Table Data                                                  :database:
 [2020-04-01 Wed 20:14]
 https://www.dolthub.com/blog/2020-04-01-how-dolt-stores-table-data/
** Journaling with Org                                                         :org:
 [2020-04-01 Wed 09:10]
 http://howardism.org/Technical/Emacs/journaling-org.html
** Kubernetes IDE                                                              :misc:
 [2020-04-01 Wed 08:44]
 https://k8slens.dev/
** Arthur Charpentier's course                                                 :statistics:
 [2020-03-31 Tue 20:23]
 https://github.com/freakonometrics/STT5100
** Stata kernel magics                                                         :stata:
 [2020-03-31 Tue 20:23]
 https://github.com/kylebarron/stata_kernel/blob/master/docs/src/using_stata_kernel/magics.md
** Mathematica vs. R                                                           :mathematica:rstats:
 [2020-03-31 Tue 20:22]
 https://github.com/antononcube/MathematicaVsR
** Vim for VS Code users                                                       :vim:
 [2020-03-30 Mon 18:27]
 https://www.freecodecamp.org/news/vim-for-people-who-use-visual-studio-code/
** Economics and geospatial analysis (IPython + Stata)                         :econ:
 [2020-03-30 Mon 17:02]
 https://econgrowth.github.io/pages/Computation.html
** Macroeconomics (Stata + IPython)                                            :python:econ:
 [2020-03-30 Mon 17:01]
 https://macroeconomics.github.io/pages/Computation.html
** Bob Jenkins' ISAAC-32 and ISAAC-64 algorithms, fast cryptographic RNGs      :cryptography:
 [2020-03-24 Tue 17:30]
 https://github.com/thephoeron/cl-isaac
** Optimized, pure Common Lisp linear-algebra library                          :lisp:
 [2020-03-24 Tue 17:28]
 https://github.com/nklein/gauss
** Computational Statistics                                                    :statistics:
 [2020-03-24 Tue 09:13]
 https://statweb.stanford.edu/~susan/courses/s227/
** profile.do - useful startups?                                               :stata:
 [2020-03-22 Sun 09:38]
 https://www.statalist.org/forums/forum/general-stata-discussion/general/1405778-profile-do-useful-startups
** Generic start of a Stata .do file                                           :stata:
 [2020-03-22 Sun 09:33]
 https://blog.uvm.edu/tbplante/2017/08/10/generic-start-of-stata-do-file/
** pandoc-based layout workflow for scholarly journals                         :pandoc:
 [2020-03-21 Sat 09:08]
 https://github.com/piero-g/markdown-workflow
** Parametric Survival Distributions                                           :rstats:
 [2020-03-19 Thu 09:17]
 https://github.com/zrmacc/Temporal
** 300 free MIT-licensed high-quality SVG icons                                :misc:
 [2020-03-19 Thu 09:14]
 https://github.com/tabler/tabler-icons
** CHICKEN's numeric tower: part 5                                             :scheme:
 [2020-03-12 Thu 16:14]
 https://www.more-magic.net/posts/numeric-tower-part-5.html
** A (mostly) comprehensive guide to calling C from Scheme and vice versa      :scheme:clang:
 [2020-03-12 Thu 14:50]
 https://www.more-magic.net/posts/scheme-c-integration.html
** Chicken Scheme, and FFI                                                     :scheme:
 [2020-03-12 Thu 13:39]
 https://demonastery.org/2011/01/chicken-scheme-and-ffi/
** MurmurHash2 (64bit) implementation                                          :rust:cryptography:
 [2020-03-12 Thu 12:28]
 https://github.com/badboy/murmurhash64-rs
** SMHasher                                                                    :cryptography:
 [2020-03-12 Thu 12:17]
 https://github.com/aappleby/smhasher
** Resources For Novel Coronavirus COVID-19                                    :mathematica:
 [2020-03-12 Thu 11:58]
 https://community.wolfram.com/groups/-/m/t/1872608
** "Big Data" formats/techniques for informatics programming                   :bioinformatics:
 [2020-03-11 Wed 15:58]
 https://github.com/molpopgen/BigDataFormats
** Uncluttered Stata Graphs                                                    :stata:
 [2020-03-11 Wed 15:31]
 https://github.com/graykimbrough/uncluttered-stata-graphs/blob/master/examples/sample_labeled_uncluttered_graph.do
** Pairwise sequence alignment in Biopython                                    :bioinformatics:python:
 [2020-03-11 Wed 12:29]
 http://biopython.org/DIST/docs/tutorial/Tutorial.html#sec:pairwise
** Novel Coronavirus (COVID-19) Cases, provided by JHU CSSE                    :misc:
 [2020-03-11 Wed 11:45]
 https://github.com/CSSEGISandData/COVID-19
** Big alignments, do they make sense?                                         :bioinformatics:
 [2020-03-11 Wed 11:35]
 https://www.drive5.com/muscle/manual/bigalignments.html
** 5 lesser-known pandas tricks                                                :python:
 [2020-03-11 Wed 11:35]
 https://towardsdatascience.com/5-lesser-known-pandas-tricks-e8ab1dd21431
** The Newick tree format                                                      :bioinformatics:
 [2020-03-11 Wed 10:57]
 http://evolution.genetics.washington.edu/phylip/newicktree.html
** Multiple Sequence Alignment                                                 :bioinformatics:
 [2020-03-11 Wed 10:48]
 https://www.ebi.ac.uk/Tools/msa/
** Open Data Kit                                                               :misc:
 [2020-03-11 Wed 10:03]
 http://opendatakit.org/
** Stata commands designed for Impact Evaluations                              :stata:
 [2020-03-11 Wed 10:03]
 https://github.com/worldbank/ietoolkit
** Rho is yet another array/dataframe package                                  :lisp:
 [2020-03-11 Wed 09:29]
 https://github.com/blindglobe/rho
** Memory-Efficient Search Trees for Database Management Systems (PDF)         :database:
 [2020-03-11 Wed 09:00]
 http://reports-archive.adm.cs.cmu.edu/anon/2020/CMU-CS-20-101.pdf
** A binary interface let Chez Scheme use Python, Lua, Ruby etc's library      :scheme:
 [2020-03-10 Tue 16:14]
 https://guenchi.github.io/Darkart/
** Scheme for scientific computing                                             :scheme:
 [2020-03-10 Tue 14:52]
 http://fmnt.info/blog/20181029_scheme.html
** Python instead of Lisp                                                      :python:lisp:
 [2020-03-10 Tue 11:36]
 https://www.tfeb.org/fragments/2016/06/09/python-instead-of-lisp/
** Macros in Racket, part one                                                  :racket:
 [2020-03-10 Tue 11:33]
 https://www.tfeb.org/fragments/2015/01/13/macros-in-racket-part-one/
** Writing syntax-case Macros                                                  :racket:
 [2020-03-10 Tue 11:33]
 https://blog.racket-lang.org/2011/04/writing-syntax-case-macros.html
** Suppressing Warnings in GCC and Clang                                       :clang:
 [2020-03-06 Fri 09:47]
 https://nelkinda.com/blog/suppress-warnings-in-gcc-and-clang/
** Modern Regression with R                                                    :rstats:
 [2020-03-05 Thu 12:23]
 http://www.stat.cmu.edu/~cshalizi/mreg/15/
** Single-Pass Online Statistics Algorithms                                    :numerical:
 [2020-03-04 Wed 15:35]
 http://www.numericalexpert.com/articles/single_pass_stat/
** The Britney Spears Problem                                                  :misc:
 [2020-03-04 Wed 15:32]
 https://www.americanscientist.org/article/the-britney-spears-problem
** Canonical Correlation Analysis in Detail                                    :statistics:
 [2020-03-04 Wed 15:26]
 https://gregorygundersen.com/blog/2018/07/17/cca/#2-scale-invariance
** Simple command-line utility to convert CSV files to HTML table              :python:
 [2020-03-04 Wed 11:20]
 https://github.com/vividvilla/csvtotable
** treespace: exploration of landscapes of phylogenetic trees                  :rstats:bioinformatics:
 [2020-03-03 Tue 16:25]
 https://thibautjombart.github.io/treespace/
** Outbreak analytics                                                          :statistics:
 [2020-03-03 Tue 16:11]
 https://royalsocietypublishing.org/doi/10.1098/rstb.2018.0276
** The Log-Sum-Exp Trick. See also https://stats.stackexchange.com/q/105602    :misc:
   :PROPERTIES:
   :ID:       0DE0C998-08ED-4471-88E3-42127C2F4B36
   :END:
 [2020-03-03 Tue 13:33]
 https://gregorygundersen.com/blog/2020/02/09/log-sum-exp/
** Compare tree topologies (Newick) using Python ete3                          :python:bioinformatics:
   :PROPERTIES:
   :ID:       57C6279E-6484-44AB-8F9B-D7A73A5C0F00
   :END:
 [2020-03-03 Tue 11:22]
 https://www.biostars.org/p/179195/
** A minimalist Hugo theme for writers and bloggers                            :hugo:
   :PROPERTIES:
   :ID:       6F45FFF4-6D1B-4ED6-A16C-7B3334FA763A
   :END:
 [2020-03-03 Tue 10:40]
 https://github.com/kimcc/hugo-theme-noteworthy
** Postgres Explain Visualizer 2                                               :database:
   :PROPERTIES:
   :ID:       9D889D63-FFAC-4313-9B6B-D39BB0B88A0B
   :END:
 [2020-03-03 Tue 09:41]
 https://github.com/dalibo/pev2
** Python/Django ED Questionnaire                                              :python:django:
   :PROPERTIES:
   :ID:       6F00AC3D-9090-4142-9C30-89D016DC11DE
   :END:
 [2020-03-02 Mon 15:00]
 https://github.com/eldest-daughter/ed-questionnaire
** Django survey creator                                                       :python:django:
   :PROPERTIES:
   :ID:       0F6BDBF6-7DCF-463D-BB7A-224FC7BF064F
   :END:
 [2020-03-02 Mon 14:48]
 https://github.com/Pierre-Sassoulas/django-survey
** String match in sliding window                                              :algorithms:
   :PROPERTIES:
   :ID:       A3103D34-58C0-4E62-9EEE-D2A492548699
   :END:
 [2020-02-28 Fri 14:09]
 https://stackoverflow.com/questions/15151628/string-match-in-sliding-window
** Scheme Natural Language Toolkit                                             :racket:nlp:
   :PROPERTIES:
   :ID:       257E419D-5FB7-481E-A289-E1AB67D05F4A
   :END:
 [2020-02-28 Fri 12:32]
 https://github.com/dcavar/SNLTK
** Simple NLP toolkit for an undergraduate class in Racket                     :racket:nlp:
   :PROPERTIES:
   :ID:       78DADA44-797D-4BD2-A10C-859F44E8A79C
   :END:
 [2020-02-28 Fri 12:25]
 https://github.com/wboag/Scheme-NLP
** Practical Racket: Using a JSON REST API                                     :racket:
   :PROPERTIES:
   :ID:       47907AC0-7504-4364-902F-7894F1CC5CA9
   :END:
 [2020-02-28 Fri 12:23]
 https://medium.com/chris-opperwall/practical-racket-using-a-json-rest-api-3d85eb11cc2d
** Càdlàg                                                                      :maths:
   :PROPERTIES:
   :ID:       73EA278F-7F84-4282-AB15-654AD6E07462
   :END:
 [2020-02-28 Fri 11:07]
 https://en.wikipedia.org/wiki/C%C3%A0dl%C3%A0g
** SHA1 and random IDs                                                         :algorithms:
   :PROPERTIES:
   :ID:       6130FA58-7300-4B80-977E-9B15A302CA8B
   :END:
 [2020-02-28 Fri 09:52]
 https://stackoverflow.com/questions/9407892/how-to-generate-random-sha1-hash-to-use-as-id-in-node-js/14869745#14869745
** How many imputations do you need?                                           :statistics:
   :PROPERTIES:
   :ID:       660D28FD-062D-47D9-8925-8198468E2FCA
   :END:
 [2020-02-27 Thu 13:57]
 https://statisticalhorizons.com/how-many-imputations
** A Racket package for playing the TwixT board game                           :racket:
   :PROPERTIES:
   :ID:       1A7221B4-9C62-423D-B9B0-4C422DF7003E
   :END:
 [2020-02-27 Thu 13:57]
 https://github.com/jackfirth/twixt
** Examples using emacs org mode babel inline source code                      :emacs:org:
   :PROPERTIES:
   :ID:       B5BFEA18-96BF-4FD4-8211-66E4A6C7CBD7
   :END:
 [2020-02-26 Wed 20:32]
 https://github.com/dfeich/org-babel-examples
** Vim Cheat Sheet                                                             :vim:
   :PROPERTIES:
   :ID:       DDBB121E-2AD1-4DF8-AC05-7D9B82C3EFEF
   :END:
 [2020-02-26 Wed 14:40]
 https://vim.rtorr.com/
** Numpy-style docstring                                                       :python:numpy:
   :PROPERTIES:
   :ID:       30765F41-AACB-4AFE-9E46-9F57D595C720
   :END:
 [2020-02-26 Wed 13:25]
 https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard
** Likelihood of a tree                                                        :bioinformatics:
   :PROPERTIES:
   :ID:       6F686781-FED4-44A2-AF29-00433C0978CC
   :END:
 [2020-02-26 Wed 11:33]
 https://www.cs.rice.edu/~ogilvie/comp571/2019/11/27/likelihood-of-a-tree.html
** Tree comparisons                                                            :bioinformatics:
   :PROPERTIES:
   :ID:       2F00A3B8-05ED-46EB-A85B-A7072BA5DFDD
   :END:
 [2020-02-26 Wed 11:12]
 https://www.cs.rice.edu/~ogilvie/comp571/2018/10/18/tree-metrics.html
** Rainbowing a set of pictures                                                :rstats:
   :PROPERTIES:
   :ID:       B530FEAB-E0B4-4B3F-9D20-F114E3D46622
   :END:
 [2020-02-25 Tue 13:42]
 https://masalmon.eu/2018/01/07/rainbowing/
** Create fractal trees using R                                                :rstats:
   :PROPERTIES:
   :ID:       5BC10AC4-EC0E-4FF3-9AF8-7E3E686DAC93
   :END:
 [2020-02-25 Tue 13:33]
 https://github.com/andrie/fractaltree/
** Modern, functional Common Lisp: Myths and best practices                    :lisp:
   :PROPERTIES:
   :ID:       0D4FF9F8-7E89-40C2-8352-452C1826D07B
   :END:
 [2020-02-25 Tue 13:15]
 https://ambrevar.xyz/modern-common-lisp/index.html
** align genomic features with phylogenetic tree                               :bioinformatics:
   :PROPERTIES:
   :ID:       1B204FC5-6F4E-4CFD-9828-428726554E45
   :END:
 [2020-02-24 Mon 15:37]
 http://guangchuangyu.github.io/2016/11/align-genomic-features-with-phylogenetic-tree/
** Creating Cyclic Data in Racket                                              :racket:
   :PROPERTIES:
   :ID:       E79C5669-07E7-47E6-8786-CCBAA25CD47A
   :END:
 [2020-02-24 Mon 15:17]
 http://jeapostrophe.github.io/2013-12-02-sharish-post.html
** Sequence simulator                                                          :bioinformatics:
   :PROPERTIES:
   :ID:       48871E92-339B-4EFA-ADB7-6A2CF74F2A81
   :END:
 [2020-02-24 Mon 13:43]
 https://github.com/rambaut/Seq-Gen
** bootstrap supports in large phylogenies                                     :bioinformatics:
   :PROPERTIES:
   :ID:       10447636-FC95-4A82-81D6-344215719956
   :END:
 [2020-02-24 Mon 13:35]
 https://github.com/evolbioinfo/booster
** E Ink color theme for Emacs                                                 :emacs:
   :PROPERTIES:
   :ID:       026180F8-8D5C-4BBD-9FB3-67D04A4B4FD7
   :END:
 [2020-02-21 Fri 14:57]
 https://github.com/maio/eink-emacs
** Neovim Clojure(Script) tooling over prepl                                   :vim:clojure:
   :PROPERTIES:
   :ID:       D79DFA03-3C80-49C5-B43B-27D64A27DAF3
   :END:
 [2020-02-21 Fri 14:21]
 https://github.com/Olical/conjure
** Genome Interval Arithmetic in R                                             :bioinformatics:rstats:
   :PROPERTIES:
   :ID:       35D28502-8EA2-4989-A40B-A7EA40222137
   :END:
 [2020-02-21 Fri 12:30]
 https://github.com/KlausVigo/valr
** Embedded database in Rust                                                   :database:rust:
   :PROPERTIES:
   :ID:       17C2D2AA-4E8D-4B97-BA4B-2AB640CD81EC
   :END:
 [2020-02-21 Fri 11:19]
 https://github.com/spacejam/sled
** Bayesian Phylogenetic Analysis                                              :bioinformatics:bayesian:
   :PROPERTIES:
   :ID:       0D8FC7D8-584D-4F03-A9B2-774E12E21431
   :END:
 [2020-02-13 Thu 14:09]
 http://www.cbs.dtu.dk/dtucourse/cookbooks/gorm/27615/bayes1.php
** Tutorial on Bayesian phylogenetic analysis                                  :bioinformatics:bayesian:
   :PROPERTIES:
   :ID:       13DF1278-79D9-4E54-8245-51C4E9C1BC5E
   :END:
 [2020-02-13 Thu 14:05]
 https://github.com/thednainus/Bayesian_tutorial
** Competitive Programming snippets                                            :algorithms:
   :PROPERTIES:
   :ID:       AD3C22FE-4D30-4FEC-A741-F97F41D79FAA
   :END:
 [2020-02-12 Wed 11:30]
 https://github.com/sei40kr/competitive-programming-snippets/tree/4c59790fefa8d717f9c3d6bdeb9b4bfd3e039cbc
** M-EMACS, a customized full-featured GNU Emacs configuration                 :emacs:
   :PROPERTIES:
   :ID:       E2DEE741-03B3-415C-9871-6780AD835617
   :END:
 [2020-02-11 Tue 11:03]
 https://github.com/MatthewZMD/.emacs.d
** Is a Dataframe Just a Table?                                                :statistics:
   :PROPERTIES:
   :ID:       505CEBB3-FB55-4FE0-AC6B-4754B237E880
   :END:
 [2020-02-11 Tue 10:30]
 https://plateau-workshop.org/assets/papers-2019/10.pdf
** Automatic parallelization with @jit                                         :python:
   :PROPERTIES:
   :ID:       27DB6CA9-DCC4-438E-B007-CEB22CB9F943
   :END:
 [2020-02-10 Mon 16:17]
 http://numba.pydata.org/numba-doc/latest/user/parallel.html#numba-parallel
** Les enchères en temps réel (RTB), un système complexe                       :misc:
   :PROPERTIES:
   :ID:       0FBE2F94-66BF-45FB-BB39-C28A92118F18
   :END:
 [2020-02-07 Fri 15:41]
 missing value
** Introduction to numerical analysis                                          :numerical:
   :PROPERTIES:
   :ID:       350B543D-6BF2-4D12-B9E8-8380DD8928CA
   :END:
 [2020-02-07 Fri 13:51]
 https://github.com/mitmath/18330
** Steiner trees                                                               :python:
   :PROPERTIES:
   :ID:       BB2DB7A8-DA2C-4171-9759-FF89D9724469
   :END:
 [2020-02-07 Fri 11:18]
 https://gis.stackexchange.com/questions/307336/generating-steiner-tree-using-network-x-in-python
** Shortest path and networkx                                                  :python:graphs:
   :PROPERTIES:
   :ID:       20B4ADD5-76BA-4B3D-AE08-C55BEE7E78A0
   :END:
 [2020-02-07 Fri 11:16]
 http://cxhernandez.com/tutorials/networks/2015/03/29/shortest-path.html
** Lessons From The History Of Attacks On Secure Hash Functions                :cryptography:
   :PROPERTIES:
   :ID:       A0F86983-044A-49B3-9D22-C56DD7CDF1F0
   :END:
 [2020-02-07 Fri 11:07]
 https://electriccoin.co/blog/lessons-from-the-history-of-attacks-on-secure-hash-functions/
** Network analysis in Python                                                  :python:graphs:
   :PROPERTIES:
   :ID:       3EB7245A-91F9-44DD-A537-D67B9696B363
   :END:
 [2020-02-05 Wed 14:34]
 https://github.com/wblakecannon/DataCamp/tree/master/21-network-analysis-in-python-(part-1)
** Numpy group_by and set-operations                                           :python:numpy:
   :PROPERTIES:
   :ID:       CB0654F2-3B00-46EB-8F34-7112213DB8F5
   :END:
 [2020-02-05 Wed 14:14]
 https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP
** Docker implemented in around 100 lines of bash.                             :docker:
   :PROPERTIES:
   :ID:       C9E45947-38C1-4202-A943-A2AE77343600
   :END:
 [2020-02-05 Wed 09:12]
 https://github.com/p8952/bocker/blob/master/README.md
** Using Emacs and Org Mode                                                    :emacs:org:
   :PROPERTIES:
   :ID:       24470BB4-4CC5-479B-95EF-9320F6B29EB9
   :END:
 [2020-02-04 Tue 17:13]
 https://edom.github.io/emacs.html
** LightGBM                                                                    :ml:
   :PROPERTIES:
   :ID:       04273433-C2AE-41B0-AA49-2A1EED54231E
   :END:
 [2020-02-04 Tue 14:10]
 https://github.com/Microsoft/LightGBM
** Phylogenetic trees in Mathematica                                           :bioinformatics:mathematica:
   :PROPERTIES:
   :ID:       DBDBAB28-B4F7-4638-BEDA-78FCF72B9066
   :END:
 [2020-02-04 Tue 13:54]
 https://mathematica.stackexchange.com/questions/126496/how-to-work-with-phylogenetic-trees
** NULL Values in SQL Queries                                                  :sql:
   :PROPERTIES:
   :ID:       8A466E33-4D68-4965-AAA3-11EAD24DC62D
   :END:
 [2020-02-04 Tue 10:29]
 https://mitchum.blog/null-values-in-sql-queries/
** Access your device's terminal from anywhere via the web                     :misc:
   :PROPERTIES:
   :ID:       6E08324D-2D63-46A9-B7DB-C3FE41302E74
   :END:
 [2020-02-04 Tue 10:28]
 https://github.com/zhaojh329/rtty
** Pathfinding Demystified                                                     :graphs:
   :PROPERTIES:
   :ID:       6CF77F05-75F5-49DD-B11D-6D7EDCA746B8
   :END:
 [2020-02-04 Tue 10:26]
 https://gabrielgambetta.com/generic-search.html
** Python package supporting heavy functional programming through currying     :python:
   :PROPERTIES:
   :ID:       D0C3F993-A330-40F1-9394-03C7864C2F66
   :END:
 [2020-02-03 Lun 17:09]
 https://github.com/jackfirth/pyramda
** Racket package template ready for Github                                    :racket:
   :PROPERTIES:
   :ID:       CCEF9AE6-2809-4C44-B6DC-5FF3F4092407
   :END:
 [2020-02-03 Lun 17:08]
 https://github.com/jackfirth/racket-package-template
** Looping in Scheme                                                           :scheme:
   :PROPERTIES:
   :ID:       BE97043C-BDC4-4994-9944-3FF1C346580D
   :END:
 [2020-01-31 Fri 07:59]
 36:39: execution error: Non autorisé à envoyer des événements Apple à Safari. (-1743)
** One-Hour Package (#rstats)                                                  :rstats:
   :PROPERTIES:
   :ID:       AEE93FCE-BE48-4FBA-9F4E-058545705573
   :END:
 [2020-01-30 Jeu 14:55]
 https://enpiar.com/2017/08/11/one-hour-package/
** Columnar File Performance Check-in: Parquet, Feather, and FST               :python:rstats:
   :PROPERTIES:
   :ID:       1F6577DC-F546-4C5A-8F8F-F52AC9487116
   :END:
 [2020-01-30 Jeu 14:52]
 https://ursalabs.org/blog/2019-10-columnar-perf/
** Introducing Apache Arrow Flight: A Framework for Fast Data Transport        :arrow:
   :PROPERTIES:
   :ID:       EFF072B8-5A33-477F-B051-537957FFBBF7
   :END:
 [2020-01-30 Jeu 14:51]
 https://arrow.apache.org/blog/2019/10/13/introducing-arrow-flight/
** Speeding up R and Apache Spark using Apache Arrow                           :arrow:rstats:
   :PROPERTIES:
   :ID:       08C771B1-B476-4E70-AFBB-138A9623C926
   :END:
 [2020-01-30 Jeu 14:21]
 https://arrow.apache.org/blog/2019/01/25/r-spark-improvements/
** Command-line Tools can be 235x Faster than your Hadoop Cluster              :hadoop:cli:
   :PROPERTIES:
   :ID:       7541AC54-C5A8-41A9-85B6-F00095112B5C
   :END:
 [2020-01-30 Jeu 10:37]
 https://adamdrake.com/command-line-tools-can-be-235x-faster-than-your-hadoop-cluster.html
** Sorting algorithms in C                                                     :algorithms:clang:
   :PROPERTIES:
   :ID:       A8D76A87-94B4-4FFE-8246-68D6C6B508C8
   :END:
 [2020-01-30 Jeu 10:36]
 https://github.com/ismdeep/sort-algos-c
** Find number of times a string occurs as a subsequence in given string       :algorithms:
   :PROPERTIES:
   :ID:       493B5663-7E90-4FAF-A87F-61427CA99C53
   :END:
 [2020-01-29 Mer 16:46]
 https://www.geeksforgeeks.org/find-number-times-string-occurs-given-string/
** Introduction to Random Strings                                              :algorithms:
   :PROPERTIES:
   :ID:       226229C8-AA3A-4E58-8DF2-7E0AA03EA6F6
   :END:
 [2020-01-29 Mer 13:30]
 https://saradoesbioinformatics.blogspot.com/2016/07/introduction-to-random-strings.html
** Chaos Game Representation of a genetic sequence                             :bioinformatics:
   :PROPERTIES:
   :ID:       2A35A1B7-2D43-49A0-BB83-D904EE73D4F4
   :END:
 [2020-01-29 Mer 12:29]
 https://towardsdatascience.com/chaos-game-representation-of-a-genetic-sequence-4681f1a67e14
** Standard prelude for Scheme (Programming Praxis)                            :scheme:
   :PROPERTIES:
   :ID:       6B2D0823-A44D-476F-B1C6-5A0FC05BF2C1
   :END:
 [2020-01-28 Mar 16:00]
 https://programmingpraxis.com/contents/standard-prelude/
** Standard Prelude for Haskell 98                                             :haskell:
   :PROPERTIES:
   :ID:       6DB5C512-10F1-4355-99F3-3EE28B06A817
   :END:
 [2020-01-28 Mar 15:59]
 https://www.haskell.org/onlinereport/standard-prelude.html
** Utilities for Gene Ontology enrichment analysis (C + Python)                :bioinformatics:
   :PROPERTIES:
   :ID:       9B33D3BD-496F-47D8-9AAD-BB6E25343016
   :END:
 [2020-01-28 Mar 10:36]
 https://github.com/thecodingdoc/GOUtil
** Toolkit for genome assembly (feat. P. anserina)                             :bioinformatics:
   :PROPERTIES:
   :ID:       76C17EBB-8A9E-4448-8A3B-F4F41058A2B5
   :END:
 [2020-01-27 Lun 16:54]
 https://blobtoolkit.genomehubs.org/
** Fun with Forms (Django)                                                     :python:django:
   :PROPERTIES:
   :ID:       3ADBE1C7-5874-4DC8-97A6-AF750C75DBD4
   :END:
 [2020-01-27 Lun 16:21]
 https://www.tangowithdjango.com/book/chapters/forms.html
** GO Enrichment Analysis (using Galaxy)                                       :bioinformatics:
   :PROPERTIES:
   :ID:       75E88F4A-D506-4B9F-BFEF-6BE8787756CE
   :END:
 [2020-01-27 Lun 12:58]
 https://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/goenrichment/tutorial.html
** Probability of finding a particular sequence of base pairs                  :bioinformatics:
   :PROPERTIES:
   :ID:       86ADA7BD-F71C-453A-93FF-159AF5FB4DD4
   :END:
 [2020-01-23 Jeu 15:40]
 https://stats.stackexchange.com/questions/26988/probability-of-finding-a-particular-sequence-of-base-pairs
** Probability Of Finding A Dna Sequence In A Window                           :bioinformatics:
   :PROPERTIES:
   :ID:       A7575339-593A-4FE3-8D48-D84300D204D4
   :END:
 [2020-01-23 Jeu 15:21]
 https://www.biostars.org/p/69354/
** Why are you changing gc-cons-threshold?                                     :emacs:
   :PROPERTIES:
   :ID:       B13887B6-7F5B-4116-8378-202DCC5854C9
   :END:
 [2020-01-22 Mer 15:12]
 http://bling.github.io/blog/2016/01/18/why-are-you-changing-gc-cons-threshold/
** UnicodeMath: A Nearly Plain-Text Encoding of Mathematics                    :maths:misc:
   :PROPERTIES:
   :ID:       A30565D3-2507-4AE3-B4FC-67779A0EC3C6
   :END:
 [2020-01-22 Mer 14:47]
 https://www.unicode.org/notes/tn28/UTN28-PlainTextMath-v3.1.pdf
** Ten Little Algorithms, Part 1: Russian Peasant Multiplication               :algorithms:
   :PROPERTIES:
   :ID:       7AE793C9-B2E6-4908-ABA8-3AA0E0771B6D
   :END:
 [2020-01-22 Mer 12:43]
 https://www.embeddedrelated.com/showarticle/760.php
** Arithmetic articles, problems, and puzzles                                  :maths:
   :PROPERTIES:
   :ID:       3EC09A4B-FEB2-421D-A588-ABAC95A3433E
   :END:
 [2020-01-22 Mer 11:31]
 https://www.cut-the-knot.org/arithmetic.shtml
** Le tutoriel Python                                                          :python:
   :PROPERTIES:
   :ID:       B96CF16C-0212-4F4F-B588-BD7781B2A545
   :END:
 [2020-01-22 Mer 09:13]
 https://docs.python.org/fr/3/tutorial/index.html
** Global alignment and alignment extension                                    :bioinformatics:
   :PROPERTIES:
   :ID:       3078CF97-6EE7-4C99-92C9-6498911DBD9A
   :END:
 [2020-01-21 Mar 16:47]
 https://github.com/lh3/ksw2
** Cleanup virtualfish env after Homebrew upgrade                              :python:cli:
   :PROPERTIES:
   :ID:       40099253-F7FF-4B62-9FDB-22A8D4F4C758
   :END:
 [2020-01-21 Mar 15:06]
 https://stackoverflow.com/questions/23233252/broken-references-in-virtualenvs
** Rope (data structure)                                                       :algorithms:
   :PROPERTIES:
   :ID:       4D2A9DDA-434B-4827-BDC6-F7E742D14DBA
   :END:
 [2020-01-21 Mar 13:56]
 https://en.wikipedia.org/wiki/Rope_(data_structure)
** A Definition of Closures                                                    :lisp:
   :PROPERTIES:
   :ID:       9BC47136-8BFF-4F54-8B5B-87042FD14A01
   :END:
 [2020-01-21 Mar 13:51]
 http://gafter.blogspot.com/2007/01/definition-of-closures.html
** UNIX Syscalls                                                               :unix:
   :PROPERTIES:
   :ID:       DEE9E033-30EC-411C-9B37-D7AA3D232C13
   :END:
 [2020-01-21 Mar 13:00]
 http://fungi-db.herokuapp.com/view/956
** Obfuscated Vim code                                                         :vim:
   :PROPERTIES:
   :ID:       D24E671E-3AFB-4C3B-9AF7-26FB100F1E17
   :END:
 [2020-01-21 Mar 12:29]
 https://www.linusakesson.net/programming/vim/index.php
** Fun with .Rprofile and customizing R startup                                :rstats:
   :PROPERTIES:
   :ID:       566F5F08-B411-4BEF-B49A-C1DA051F77A3
   :END:
 [2020-01-21 Mar 11:57]
 https://www.r-bloggers.com/fun-with-rprofile-and-customizing-r-startup/
** Nice org config for Doom Emacs                                              :emacs:
   :PROPERTIES:
   :ID:       86F7E323-8CA4-4CC2-BBB2-4C684CCC18D0
   :END:
 [2020-01-21 Mar 09:50]
 https://github.com/nmartin84/.doom.d
** xsv for indexing, slicing, analyzing, splitting and joining CSV files.      :misc:
   :PROPERTIES:
   :ID:       BE4EBCDE-87CE-48E6-9DA9-28A7E2DB062D
   :END:
 [2020-01-20 Lun 14:27]
 https://github.com/BurntSushi/xsv
** Why is quicksort better than other sorting algorithms in practice?          :algorithms:
   :PROPERTIES:
   :ID:       F6AB06B2-AC16-433E-8C0E-0E38F095BED3
   :END:
 [2020-01-20 Lun 14:23]
 https://cs.stackexchange.com/questions/3/why-is-quicksort-better-than-other-sorting-algorithms-in-practice
** Ergolib to make programming in Common Lisp easier.                          :lisp:
 [2020-01-20 Lun 12:28]
 https://github.com/rongarret/ergolib
** Lisping at JPL                                                              :lisp:
 [2020-01-20 Lun 12:26]
 http://flownet.com/gat/jpl-lisp.html
** R7RS SRFI implementations                                                   :scheme:
   :PROPERTIES:
   :ID:       99259404-1186-4D3B-900B-31A0B1DD2214
   :END:
 [2020-01-17 Ven 09:55]
 https://github.com/TaylanUB/scheme-srfis
** New C standard online                                                       :clang:
   :PROPERTIES:
   :ID:       AF334E61-74CF-4EC4-8C51-3D47778C5720
   :END:
 [2020-01-16 Jeu 14:03]
 http://c0x.coding-guidelines.com/
** A new algorithm for finding a visual center of a polygon                    :algorithms:
   :PROPERTIES:
   :ID:       065D983B-B7AD-442A-9BFE-035D0163B1E4
   :END:
 [2020-01-15 Mer 16:44]
 https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc
** OpenGL Setup in macOS                                                       :misc:
   :PROPERTIES:
   :ID:       92787029-EAEF-4601-B3A6-350C402A229B
   :END:
 [2020-01-15 Mer 15:48]
 https://giovanni.codes/opengl-setup-in-macos/
** Using OpenGL with Common Lisp                                               :lisp:
   :PROPERTIES:
   :ID:       5C70E4EF-31ED-412C-A4AB-17D4F8C33304
   :END:
 [2020-01-15 Mer 15:47]
 https://markbrown778.wordpress.com/2013/04/14/using-opengl-with-common-lisp-and-macos-x/
** PyOxidizer is a utility for producing binaries that embed Python            :python:
   :PROPERTIES:
   :ID:       98B97236-C191-459B-B33E-C272ED776925
   :END:
 [2020-01-14 Mar 15:40]
 https://github.com/indygreg/PyOxidizer
** Why I Keep a Research Blog                                                  :misc:
   :PROPERTIES:
   :ID:       AB0432DE-F04D-40E9-9356-8DC480EA5B5A
   :END:
 [2020-01-13 Lun 16:09]
 http://gregorygundersen.com/blog/2020/01/12/why-research-blog/
** Heap in Lisp                                                                :lisp:
   :PROPERTIES:
   :ID:       597DF12D-8CCC-479E-8D02-2C66C9147E06
   :END:
 [2020-01-10 Ven 19:44]
 http://gms.freeshell.org/lisp-heap/heap.txt
** List of terms relating to algorithms and data structures                    :algorithms:
   :PROPERTIES:
   :ID:       A707DBDC-12C6-490F-B1BA-3363F79D77E3
   :END:
 [2020-01-10 Ven 14:14]
 https://en.m.wikipedia.org/wiki/List_of_terms_relating_to_algorithms_and_data_structures
** Graph structures in C                                                       :graphs:clang:
   :PROPERTIES:
   :ID:       1880D01C-3DED-411D-82E1-90ECD80199D0
   :END:
 [2020-01-10 Ven 14:08]
 https://www.techiedelight.com/implement-graph-data-structure-c/
** Parallel Processing in Python                                               :python:
   :PROPERTIES:
   :ID:       0B8A54E0-3287-48ED-94F0-25DCB730A5E0
   :END:
 [2020-01-09 Jeu 14:22]
 https://stackabuse.com/parallel-processing-in-python/
** Data science for economists                                                 :econ:
   :PROPERTIES:
   :ID:       DDACF1F5-448A-4C1B-A366-B3363DA1CF3E
   :END:
 [2020-01-09 Jeu 10:35]
 https://github.com/uo-ec607/lectures
** Parallel programming using R                                                :rstats:
   :PROPERTIES:
   :ID:       EBD078FF-4EAD-4FCB-A480-205C497BAEFA
   :END:
 [2020-01-09 Jeu 10:33]
 https://raw.githack.com/uo-ec607/lectures/master/12-parallel/12-parallel.html#beware_resource_competition
** Scientific computing with Rust                                              :rust:
   :PROPERTIES:
   :ID:       C6A81828-DD6F-44D7-9DAF-D045E59AA5AF
   :END:
 [2020-01-08 Mer 14:27]
 https://rust-sci.github.io/
** Rust crates for numerical simulation                                        :rust:numerical:
   :PROPERTIES:
   :ID:       C870B658-9B7B-4A21-B991-DBCB46C3E273
   :END:
 [2020-01-08 Mer 14:25]
 https://rustsim.org/
** Convert .py to .exe                                                         :python:cli:
   :PROPERTIES:
   :ID:       B7147882-7981-4B8A-87B2-EDE9EC8D3989
   :END:
 [2020-01-08 Mer 12:02]
 https://nitratine.net/blog/post/convert-py-to-exe/
** ZSH higher order functions                                                  :cli:
   :PROPERTIES:
   :ID:       401DF046-A368-42AA-883E-8E8C02173CFE
   :END:
 [2020-01-07 Mar 14:34]
 https://github.com/yogsototh/zsh_functional
** Gamma function                                                                     :statistics:
   :PROPERTIES:
   :ID:       0323F358-24F3-48C3-ADF9-0E119DDE694F
   :END:
 [2020-01-07 Mar 08:09]
 https://probabilityandstats.wordpress.com/2017/08/20/the-gamma-function/
** Cryptographic libraries for R6RS Scheme                                     :cryptography:scheme:
   :PROPERTIES:
   :ID:       F29F5FF0-6820-4A0F-86FA-D9F6C856DD2F
   :END:
 [2020-01-06 Lun 11:46]
 https://github.com/weinholt/industria
** Algebric data types and unordered effects                                   :cattheo:
   :PROPERTIES:
   :ID:       08EDD394-A676-4550-96D3-443B2F87640E
   :END:
 [2020-01-06 Lun 11:24]
 https://www.reddit.com/r/haskell/comments/ej8fme/unordered_effects/fd00mk2/
** Why do Racket hash literals (i.e. #hash()) automatically quote              :racket:
   :PROPERTIES:
   :ID:       6C09B3DB-725D-4F96-862B-9B0C23D16E79
   :END:
 [2020-01-06 Lun 11:22]
 https://www.reddit.com/r/Racket/comments/ehwz0j/why_do_racket_hash_literals_ie_hash_automatically/fcmb1e5/?context=3
** Neighbour sensing model for fungi growth                                    :bioinformatics:
 [2019-12-18 Wed 12:07]
 http://www.davidmoore.org.uk/CyberWEB/Cyber04.htm
** Generative Hyphae Growth Algorithm                                          :algorithms:
 [2019-12-18 Wed 12:01]
 https://github.com/shaanappel/generative-hyphae-3d
** Hyphal branching using Processing                                           :processing:
 [2019-12-18 Wed 11:13]
 http://www.iaacblog.com/programs/introduction-processing-hyphal-branching/
** Xylem and hyphae network                                                    :bioinformatics:
 [2019-12-18 Wed 11:10]
 https://n-e-r-v-o-u-s.com/blog/?p=1218
** Let's Write an LLVM Specializer for Python!                                 :python:llvm:
 [2019-12-18 Wed 10:58]
 http://dev.stephendiehl.com/numpile/
** Implementing a JIT Compiled Language with Haskell and LLVM                  :haskell:llvm:
 [2019-12-18 Wed 10:56]
 http://www.stephendiehl.com/llvm/
** Step-by-Step Guide to Implement Machine Learning                            :ml:
 [2019-12-17 Tue 08:30]
 https://www.codeproject.com/Articles/5061034/Step-by-Step-Guide-to-Implement-Machine-Learning-6
** The Racket Foreign-Function Interface                                       :racket:
 [2019-12-16 Mon 16:23]
 http://www.cs.grinnell.edu/~rebelsky/Glimmer/Summer2012/RacketFFI/tutorial.html
** Tutorial: Using Racket’s FFI (3 parts)                                      :racket:
 [2019-12-16 Mon 15:59]
 http://prl.ccs.neu.edu/blog/2016/06/27/tutorial-using-racket-s-ffi/
** Tutorial: Using Racket’s FFI                                                :racket:
 [2019-12-16 Mon 13:51]
 https://prl.ccs.neu.edu/blog/2016/06/27/tutorial-using-racket-s-ffi/
** A (mostly) comprehensive guide to calling C from Scheme and vice versa      :scheme:clang:
 [2019-12-16 Mon 13:49]
 https://www.more-magic.net/posts/scheme-c-integration.html
** Dash Bio is a suite of bioinformatics components                            :plotly:
 [2019-12-13 Fri 10:42]
 https://github.com/plotly/dash-bio
** Heroku buildpack for R                                                      :heroku:rstats:
 [2019-12-13 Fri 10:41]
 https://github.com/virtualstaticvoid/heroku-buildpack-r/tree/heroku-16
** No Pain - No Gain: Using Clojure for Web Apps                               :clojure:
 [2019-12-12 Thu 18:02]
 https://github.com/tbsschroeder/using-clojure-for-web-apps
** Functional Data Structures in Typed Racket                                  :racket:
 [2019-12-11 Wed 14:45]
 https://docs.racket-lang.org/functional-data-structures/index.html
** Scheme/Racket course                                                        :racket:scheme:
 [2019-12-11 Wed 12:32]
 https://courses.cs.washington.edu/courses/cse341/18sp/racket/
** Microbenchmark in Racket                                                    :racket:
 [2019-12-10 Tue 19:39]
 https://www.travishinkelman.com/post/microbenchmarking-in-r-and-racket/
** Racket and docstrings using at-exp                                          :racket:
 [2019-12-10 Tue 16:09]
 https://stackoverflow.com/questions/58981544/docstrings-in-racket
** Challenge: find Twitter memes with suffix arrays                            :algorithms:
 [2019-12-09 Mon 14:54]
 https://jvns.ca/blog/twitter-memes-challenge/
** Pharmaceutical Modeling and Simulation for NL Mixed Effects using Julia     :julia:statistics:
 [2019-12-09 Mon 10:30]
 https://github.com/PumasAI/Pumas.jl
** Templates Django                                                            :python:django:
 [2019-12-05 Thu 20:09]
 https://tutorial.djangogirls.org/fr/template_extending/
** Django Photo Gallery Sample                                                 :python:django:
 [2019-12-04 Wed 13:37]
 https://github.com/VelinGeorgiev/django-photo-gallery
** Useful tips & tricks for R (and more)                                       :rstats:
 [2019-12-04 Wed 13:20]
 https://github.com/hbc/knowledgebase/blob/master/r/R-tips-and-tricks.md
** Genome browser tracks using Python                                          :bioinformatics:python:
 [2019-12-03 Tue 15:19]
 https://pythonawesome.com/python-module-to-plot-beautiful-and-highly-customizable-genome-browser-tracks/
** Coupled events with Shiny and Plotly in R                                   :rstats:shiny:
 [2019-11-28 Thu 16:23]
 https://plot.ly/r/shiny-coupled-events/
** Visualizing Algorithms                                                      :algorithms:
 [2019-11-27 Wed 12:52]
 https://bost.ocks.org/mike/algorithms/
** Docker Cleanup Commands                                                     :docker:
 [2019-11-26 Tue 10:41]
 https://www.calazan.com/docker-cleanup-commands/
** Neat Rust Tricks: Passing Rust Closures to C                                :rust:
 [2019-11-26 Tue 10:32]
 https://blog.seantheprogrammer.com/neat-rust-tricks-passing-rust-closures-to-c
** Scheme and Fibonacci                                                        :scheme:
 [2019-11-25 Mon 10:51]
 https://www.reddit.com/r/scheme/comments/114jaj/nth_fibonacci_numbers_with_the_golden_ratioracket/
** How to Override CSS Styles in Jekyll                                        :misc:
 [2019-11-20 Wed 16:56]
 alias: Expected at most 2 args, got 3
 https://tomkadwill.com/2017/12/16/how-to-override-css-styles-in-jekyll.html
** Fundamentals of Machine Learning Course at DSR                              :ml:
 [2019-11-20 Wed 12:53]
 https://github.com/dvgodoy/ML_Fundamentals
** Advanced Python                                                             :python:
 [2019-11-20 Wed 12:45]
 https://github.com/krother/advanced_python
** Lot of useful config for neovim/zsh/tmux                                    :vim:tmux:
 [2019-11-19 Tue 15:34]
 https://github.com/iamrecursion/dotfiles
** LSP for (neo)vim                                                            :vim:
 [2019-11-19 Tue 14:20]
 https://github.com/neoclide
** Fisher–Yates shuffle                                                        :statistics:
 [2019-11-19 Tue 13:15]
 https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle
** DendroPy Phylogenetic Computing Library                                     :bioinformatics:
 [2019-11-19 Tue 12:26]
 https://dendropy.org/
** Flask and Apache WSGI                                                       :python:flask:
 [2019-11-19 Tue 12:12]
 https://www.bogotobogo.com/python/Flask/Python_Flask_HelloWorld_App_with_Apache_WSGI_Ubuntu14.php
** Configurer un webservice Python Flask sur Apache HTTPD                      :python:flask:
 [2019-11-19 Tue 12:11]
 https://www.security-helpzone.com/2017/07/03/apache-httpd-configurer-mod_wsgi-pour-utiliser-python-3-flask/
** Recognizing graphs from images                                              :graphs:
 [2019-11-19 Tue 12:02]
 https://www.yworks.com/blog/projects-optical-graph-recognition
** Changes the current Ruby                                                    :ruby:
 [2019-11-18 Mon 11:01]
 https://github.com/postmodern/chruby
** Comparative Genomics with R                                                 :bioinformatics:rstats:
 [2019-11-18 Mon 10:38]
 https://hajkd.github.io/orthologr/index.html
** Introduction to mlr3                                                        :rstats:ml:
 [2019-11-18 Mon 10:23]
 https://github.com/mlr-org/mlr3book
** Programming For Biology 2019                                                :bioinformatics:
[2019-11-13 Wed 13:02]
https://github.com/prog4biol/pfb2019
** Programming Talks                                                           :misc:
[2019-11-07 Jeu 14:29]
https://github.com/hellerve/programming-talks#hackett
** A systematic review of health effects of electronic cigarettes              :misc:
[2019-11-07 Jeu 14:16]
https://www.who.int/tobacco/industry/product_regulation/BackgroundPapersENDS3_4November-.pdf
** Making a Simple Website with Flask                                          :python:flask:
[2019-11-05 Tue 13:21]
http://oliverelliott.org/article/computing/notes_labsite/
** AWS for Bioinformatics                                                      :bioinformatics:
[2019-11-05 Tue 13:18]
http://oliverelliott.org/article/computing/tut_bio_aws_2/
** scatterplot between a pair of 2 consecutive pseudo random numbers           :maths:
[2019-11-04 Mon 10:33]
https://stats.stackexchange.com/questions/433029/which-is-the-meaning-of-scatterplot-between-a-pair-of-2-consecutive-pseudo-rando/434151#434151
** Remote Desktop Roundup: TeamViewer vs. Splashtop vs. Windows RDP            :misc:
[2019-10-30 Wed 11:24]
https://www.howtogeek.com/257655/remote-desktop-roundup-teamviewer-vs.-splashtop-vs.-windows-rdp/
** How to Lock Down TeamViewer for More Secure Remote Access                   :misc:
[2019-10-30 Wed 11:19]
https://www.howtogeek.com/257376/how-to-lock-down-teamviewer-for-more-secure-remote-access/
** How secure is TeamViewer for simple remote support?                         :misc:
[2019-10-30 Wed 11:15]
https://security.stackexchange.com/questions/12152/how-secure-is-teamviewer-for-simple-remote-support
** Complete list of zsh themes                                                 :cli:
[2019-10-30 Wed 10:15]
https://zshthem.es/all/
** Owl Numerical System                                                        :ocaml:
[2019-10-30 Wed 09:38]
https://ocaml.xyz/chapter/index.html
** Stupid Unix Tricks                                                          :unix:cli:
[2019-10-17 Thu 17:06]
https://sneak.berlin/20191011/stupid-unix-tricks/
** How to secure remote access to a Linux server (without SSH keys)            :misc:
[2019-10-17 Thu 17:04]
https://medium.com/@chrislange/how-to-secure-remote-access-to-a-linux-server-without-ssh-keys-61a1aa099cfc
** Creating a Permanent SSH Tunnel Back to Your Mac at Home                    :misc:
[2019-10-16 Wed 12:04]
https://tyler.io/creating-a-permanent-ssh-tunnel-back-to-your-mac-at-home/
** Master Git (part 1)                                                         :git:
[2019-10-15 Tue 10:49]
http://artemstar.com/2017/03/26/git/
** How to Install and Dual Boot Linux and Mac OS                               :misc:
[2019-10-15 Tue 08:53]
https://www.lifewire.com/dual-boot-linux-and-mac-os-4125733
** How to Install Ubuntu on a MacBook Pro                                      :misc:
[2019-10-15 Tue 08:51]
https://laptop.ninja/how-to-install-ubuntu-on-a-macbook-pro/
** tmux in practice: iTerm2 and tmux                                           :tmux:cli:
[2019-10-14 Mon 16:56]
https://www.freecodecamp.org/news/tmux-in-practice-iterm2-and-tmux-integration-7fb0991c6c01/
** Tmux Cheat Sheet & Quick Reference                                          :tmux:
[2019-10-14 Mon 16:45]
https://tmuxcheatsheet.com/
** SSH and tmux                                                                :tmux:
[2019-10-14 Mon 15:22]
https://github.com/ernestk-git/data-scientist-ish/wiki/ssh-tmux?source=post_page---------------------------
** Using virtualenv with fish shell                                            :python:cli:
[2019-10-09 Wed 14:59]
https://riptutorial.com/python/example/9956/using-virtualenv-with-fish-shell
** Teaching Materials for genome assembly and mapping                          :bioinformatics:
[2019-10-09 Wed 13:44]
http://www.langmead-lab.org/teaching-materials/
** bcbio-nextgen                                                               :bioinformatics:
[2019-10-08 Tue 15:44]
https://bcbio-nextgen.readthedocs.io/en/latest/contents/introduction.html
** Suffix arrays: How to compute them fast with Python                         :algorithms:python:
[2019-10-08 Tue 15:25]
https://louisabraham.github.io/notebooks/suffix_arrays.html
** Accurate design of in vitro experiments -- Why does it matter?              :bioinformatics:
[2019-10-08 Tue 11:46]
https://paasp.net/accurate-design-of-in-vitro-experiments-why-does-it-matter/
** Introduction to RNA-Seq using high-performance computing                    :bioinformatics:
[2019-10-08 Tue 10:03]
https://hbctraining.github.io/Intro-to-rnaseq-hpc-salmon/schedule/
** Lectures for Mathematics 361 (feat. Number Theory)                          :maths:numtheo:
[2019-10-07 Mon 10:35]
http://people.reed.edu/~jerry/361/lectures/lec.html
** Hidden features of Python [closed]                                          :python:
[2019-10-07 Mon 10:09]
https://stackoverflow.com/questions/101268/hidden-features-of-python
** Automatic parallelization with @jit                                         :python:
[2019-10-04 Fri 14:44]
http://numba.pydata.org/numba-doc/latest/user/parallel.html#explicit-parallel-loops
** Nice tutorial on genome assembly                                            :bioinformatics:
[2019-10-02 Wed 14:17]
https://homolog.us/Tutorials/book4/p2.1.html
** More on pipe operators in R                                                 :rstats:
[2019-10-02 Wed 13:42]
https://www.datacamp.com/community/tutorials/pipe-r-tutorial
* Archives
(NOTE: in decreasing order, i.e. newer comes last)
** Check this new series of posts from Stata blog
[2018-02-15 Thu 21:01]
https://blog.stata.com/2018/02/15/programming-an-estimation-command-in-stata-preparing-to-write-a-plugin/
** See if we can make something similar to handle statistical projects and tutorials.
[2018-02-15 Thu 18:01]
http://dankleiman.com/2018/01/28/keeping-an-engineering-notebook/
** Useful stuff for "agile data science" and "design pattern for efficient data mining"
[2018-02-18 Sun 09:43]
https://www.oreilly.com/ideas/questioning-the-lambda-architecture
** Is this working?
[2018-02-19 Mon 00:13]
https://github.com/qdot/org-gitbook
** Cool stuff here. Check out other posts on CL implementation
[2018-02-19 Mon 23:18]
https://kaygun.tumblr.com/post/161636640449/a-stochastic-gradient-descent-implementation-in
** Lot of useful stuff to master iterators in Python 3
Reminds me of: Clojure High Performance -- Variations around the Fibonacci sequence using linear algorithms: https://deque.blog/2017/06/01/clojure-high-performance-fibonacci/#more-22281
[2018-02-20 Tue 12:35]
https://www.youtube.com/watch?v=ThS4juptJjQ
** Useful reading list to start diving into Haskell land
[2018-02-20 Tue 19:58]
http://www.stephendiehl.com/posts/haskell_2018.html
** Useful guide to setup Haskell for productive work
[2018-02-21 Wed 13:02]
https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
** Nice overview of resampling methods.
[2018-02-22 Thu 10:24]
https://stats.stackexchange.com/questions/104040/resampling-simulation-methods-monte-carlo-bootstrapping-jackknifing-cross
** Here is an HN thread where we learn a lot about how Mathematica was originally designed. See also this blog post: [[http://blog.stephenwolfram.com/2013/02/what-should-we-call-the-language-of-mathematica/][What Should We Call the Language of Mathematica?]]
[2018-02-24 Sat 21:35]
https://news.ycombinator.com/item?id=9797936
** Check the code on  GitHub to see if I can use it for custom handouts
[2018-03-02 Fri 19:08]
https://jblevins.org/log/dot-grid-paper
** To get inspiration for an org-based textbook. See also https://lakshminp.com/publishing-book-using-org-mode
[2018-03-05 Mon 09:39]
https://procomun.wordpress.com/2014/03/10/writing-a-book-with-emacs/
** Check the extended documentation and files in texlive
[2018-03-05 Mon 16:22]
http://petr.olsak.net/opmac-e.html
** To learn more about zip, gzip and zlib, by Marc Adler. h/t https://piotrkazmierczak.com/2016/how-are-zlib-gzip-and-zip-related/
[2018-03-05 Mon 23:54]
https://stackoverflow.com/questions/20762094/how-are-zlib-gzip-and-zip-related-what-do-they-have-in-common-and-how-are-they
** Yet another blog post about Org and GTD, specifically https://www.buildingasecondbrain.com
[2018-03-06 Tue 09:58]
https://praxis.fortelabs.co/building-a-second-brain-in-emacs-and-org-mode-faa20ae06fc
** A nice sociological account of Steve Job's life and vision of things
[2018-03-06 Tue 10:02]
https://kieranhealy.org/blog/archives/2011/10/10/a-sociology-of-steve-jobs/
** Introduction to org-ref features
[2018-03-06 Tue 10:21]
https://www.youtube.com/watch?v=2t925KRBbFc
** Why Sage is failing. Check also https://www.reddit.com/r/math/comments/45q7j1/sagemath_open_source_is_now_ready_to_compete_with/
[2018-03-06 Tue 12:39]
http://sagemath.blogspot.fr/2014/08/what-is-sagemathcloud-lets-clear-some.html
** Someone must have to write an EOS
[2018-03-06 Tue 12:57]
https://writequit.org/eos/eos.html
** Yet another org-powered blog
[2018-03-06 Tue 13:09]
https://ogbe.net/blog/blogging_with_org.html
** Useful stuff to build a custom Iosevka font type for emacs and web
[2018-03-06 Tue 13:20]
http://whyarethingsthewaytheyare.com/trying-out-iosevka-font/
** Very nice looking web site with lot of goodies inside
[2018-03-06 Tue 14:04]
https://www.baty.net/post/
** Read some blog entries
[2018-03-09 Fri 21:43]
https://pavpanchekha.com/
** Org-mode in VS Code
[2018-03-14 Wed 10:57]
https://news.ycombinator.com/item?id=16198369
** I should definitely check the scrartcl class
[2018-03-14 Wed 22:20]
https://tex.stackexchange.com/questions/295864/tufte-alike-design-with-sidenotes-crossing-pagebreaks-or-tufte-made-with-komas/352756#352756
** How does it compare to [[https://spark.apache.org/docs/latest/sql-programming-guide.html#datasets-and-dataframes][Apache Spark DataFrame]]?
[2018-03-15 Thu 21:45]
https://github.com/acowley/Frames
** Interesting Youtube channel to learn cool things about dataviz
[2018-03-16 Fri 08:32]
https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg
** Useful handouts for caluclus and probability
[2018-03-16 Fri 08:45]
http://sites.math.rutgers.edu/~zeilberg/
** To find datasets
[2018-03-16 Fri 13:43]
http://www.statsci.org/datasets.html
** Short info on how to use irony and rdm for clang stuff
[2018-04-21 Sam 23:35]
https://oremacs.com/2017/03/28/emacs-cpp-ide/
** Useful code snippet to generate reproducible random numbers in Clojure
[2018-04-23 Lun 10:29]
https://stackoverflow.com/questions/24007063/how-to-generate-repeatable-random-sequences-with-rand-int
** Implement this PRNG in Clojure
[2018-04-23 Lun 18:28]
https://www.codeproject.com/Articles/25172/Simple-Random-Number-Generation
** Constructive critic of Stephen Wolfram wrt his book "A New Kind of Science"
[2018-04-24 Mar 00:22]
https://nedbatchelder.com/blog/200207/stephen_wolframs_unfortunate_ego.html
** Implementation of Random Forest in Lisp (See also the interface to Gnuplot)
[2018-04-25 Mer 08:24]
https://github.com/masatoi/cl-random-forest
** Nice ressources on Epidemiology, including Clayton's book on Statistical Models in Epidemiology
[2018-04-26 Jeu 12:50]
http://www.med.mcgill.ca/epidemiology/hanley/bios601/
** How to disable Google chrome updater
[2018-04-30 Lun 17:28]
http://applehelpwriter.com/2014/07/13/how-to-remove-googles-secret-update-software-from-your-mac/
** Good intro to Python itertools
[2018-05-01 Mar 12:49]
https://www.blog.pythonlibrary.org/2016/04/20/python-201-an-intro-to-itertools/
** Cool Python 3.x tips & tricks
[2018-05-02 Mer 14:50]
https://sahandsaba.com/thirty-python-language-features-and-tricks-you-may-not-know.html
** Think of prioritization of endpoints as pre-specification of the order for publication and how the study results are publicized. It is OK to announce a “significant” third endpoint as long as the “insignificant” first and second endpoints are announced first, and the context for the third endpoint is preserved.
[2018-05-07 Lun 10:30]
http://www.fharrell.com/post/ymult/
** Check some of the courses and PDFs
[2018-05-08 Mar 08:51]
https://people.eecs.berkeley.edu/~wkahan/
** Useful Emacs init files (blog post here: http://www.howardism.org/Technical/Emacs/orgmode-wordprocessor.html)
[2018-05-08 Mar 08:57]
https://github.com/howardabrams/dot-files
** Interesting Swift/CBLAS link + Numpy-like methods
[2018-05-12 Sam 08:30]
https://stsievert.com/swix/
** Ressources for Stata teaching
[2018-05-12 Sam 08:30]
https://www.stata.com/links/resources-for-learning-stata/#cheat
** Quick introduction to git internals for people who are not scared by words like Directed Acyclic Graph.
[2018-05-12 Sam 08:46]
http://eagain.net/articles/git-for-computer-scientists/
** Interesting blog posts and econom(etr)ics courses using Python and Stata
[2018-05-12 Sam 09:53]
http://rlhick.people.wm.edu/posts/index.html
** See the notes section for interesting maths and number theory with algorithms
[2018-05-12 Sam 21:01]
https://crypto.stanford.edu/pbc/
** Number Theory with Python
[2018-05-13 Dim 18:49]
http://www.math.umbc.edu/~campbell/Computers/Python/numbthy.html
** Tutorial on Python Pandas by the same author of the [[http://ehneilsen.net/notebook/orgExamples/org-examples.html][org-mode tutorial]]
[2018-05-14 Lun 08:16]
http://ehneilsen.net/notebook/pandasExamples/pandas_examples.html
** Useful cheat sheet for org-mode, especially +OPTIONS keywords
[2018-05-14 Lun 08:22]
https://emacsclub.github.io/html/org_tutorial.html
** Lot of ressources on crypto/math and number theory
[2018-05-15 Mar 09:53]
http://www.math.brown.edu/~jhs/
** Looks like a nice intro to Swift
[2018-05-15 Mar 09:54]
https://www.hackingwithswift.com/read/0/overview
** Interesting tutorials on Stata by Mark Lunt
[2018-05-15 Mar 09:55]
http://personalpages.manchester.ac.uk/staff/mark.lunt/stats_course.html
** To learn a bit of Vim (again)
[2018-05-15 Mar 10:34]
https://ferd.ca/vim-and-composability.html
** Interesting R package that brings some Stata output
[2018-05-15 Mar 21:07]
https://github.com/matthieugomez/statar
** How to use org-mode with Stata code
[2018-05-15 Mar 21:18]
http://rlhick.people.wm.edu/posts/stata-and-literate-programming-in-emacs-org-mode.html
** How to custiomize HTML and CSS with org-mode
[2018-05-15 Mar 21:18]
https://emacs.stackexchange.com/questions/7629/the-syntax-highlight-and-indentation-of-source-code-block-in-exported-html-file
** Yet Another Org-Mode Configuration
[2018-05-16 Mer 10:41]
http://www.i3s.unice.fr/~malapert/org/tips/emacs_orgmode.html
** What to put in your Stata profile.do
[2018-05-16 Mer 19:47]
https://www.statalist.org/forums/forum/general-stata-discussion/general/1405778-profile-do-useful-startups
** Yet another org-mode post dedicated to Hugo
[2018-05-16 Mer 21:59]
https://www.zcl.space/tools/my-blog-workflow/
** The setup
[2018-05-18 Ven 06:32]
https://writequit.org/org/
** Plain TeX template for editing refcard
[2018-05-18 Ven 09:29]
https://michaelgoerz.net/refcards/
** Common Lisp Quick Reference is a free booklet with short descriptions of the thousand or so symbols defined in the ANSI standard
[2018-05-18 Ven 09:31]
http://clqr.boundp.org/
** Interesting package! See also {breakDown} [[https://pbiecek.github.io/breakDown/]].
[2018-05-18 Ven 14:04]
http://pbiecek.github.io/archivist/
** Check dataMaid (An R package for data screening)
[2018-05-18 Ven 14:18]
https://github.com/ekstroem/dataMaid
** Config options for org-mode with French babel
[2018-05-20 Dim 09:16]
http://drieu.org/post/R%C3%A9glages-org-mode-et-export-PDF
** Org-babel examples on GitHUb
[2018-05-20 Dim 09:46]
https://github.com/dfeich/org-babel-examples
** Free online Lisp books
[2018-05-20 Dim 23:55]
https://www.onlineprogrammingbooks.com/lisp/
** A local+cloud alternative to Dropbox
[2018-05-20 Dim 23:59]
https://syncthing.net/
** Interesting gnuplot examples
[2018-05-22 Mar 07:10]
http://www.gnuplotting.org/
** Another org config
[2018-05-23 Mer 09:44]
http://members.optusnet.com.au/~charles57/GTD/gtd_workflow.html
** Useful tips on org-mode + beautiful CSS
[2018-05-23 Mer 16:45]
http://www.cachestocaches.com/2016/9/my-workflow-org-agenda/
** Other than proselint, there is this plugin to help in detecting writing typos and the like
[2018-05-24 Jeu 15:20]
https://github.com/bnbeckwith/writegood-mode
** Interesting read
[2018-05-28 Lun 22:34]
https://arachnoid.com/trouble_with_psychology/index.html
** How to Start a Bookdown Book
[2018-05-29 Mar 07:27]
http://seankross.com/2016/11/17/How-to-Start-a-Bookdown-Book.html
** Python for NLP and machine learning
[2018-05-30 Mer 08:23]
https://github.com/TiesdeKok/Python_NLP_Tutorial
** Another tutorial on Python for accounting resarch
[2018-05-30 Mer 08:24]
https://github.com/TiesdeKok/LearnPythonforResearch
** Good old tutorial on Org + Pandoc
[2018-05-30 Mer 08:35]
https://www.rousette.org.uk/archives/org-mode-and-pandoc/
** Jupyter vs. R Markdown
[2018-05-30 Mer 18:12]
https://www.datacamp.com/community/blog/jupyter-notebook-r
** I should try to replace ipynb with Md files
[2018-05-30 Mer 18:15]
https://github.com/rossant/ipymd
** And now here is a way to convert Python notebook to RMarkdown
[2018-05-30 Mer 18:17]
https://github.com/chronitis/ipyrmd
** Interesting template for Gitbook with open review
[2018-05-30 Mer 19:08]
https://benmarwick.github.io/bookdown-ort/mods.html
** Base16 for Shells
[2018-05-30 Mer 21:35]
https://github.com/chriskempson/base16-shell
** Interesting approach with Vagrant and rstats
[2018-05-31 Jeu 09:18]
https://github.com/agoldst/litdata-vagrant
** CL and Machine Learning
[2018-05-31 Jeu 09:19]
https://github.com/mmaul/clml
** Really nice tutorial
[2018-05-31 Jeu 09:20]
https://github.com/seeingtheory/Seeing-Theory
** Useful mu4e config tips
[2018-06-01 Ven 04:01]
https://github.com/thblt/.emacs.d/blob/master/dotemacs.org
** Drowning in Email; mu4e to the Rescue
[2018-06-01 Ven 04:04]
http://www.macs.hw.ac.uk/~rs46/posts/2014-01-13-mu4e-email-client.html
** Email done right (in Emacs)
[2018-06-01 Ven 04:14]
https://zmalltalker.com/linux/mu.html
** Pretty nice idea
[2018-06-01 Ven 21:54]
https://erikclarke.net/2014/10/21/keeping-a-lab-notebook-with-org-mode-git-papers-and-pandoc-part-ii/
** In case we want to go to the dark side with Forklift
[2018-06-04 Lun 09:30]
https://johnscullen.com/how-to-make-forklift-3-the-default-file-viewer/
** Interesting application for teaching with Rosner's FEV dataset
[2018-06-04 Lun 11:01]
https://ww2.amstat.org/publications/jse/v13n2/datasets.kahn.html
** Good paper that summarizes the main point of logistic regression
[2018-06-04 Lun 19:35]
http://www.kan.or.kr/kor/shop_sun/files/memoir_img/201302/mm__201304301807550.pdf
** Useful tutorial on mixed-effect models using R
[2018-06-05 Mar 07:25]
http://rpsychologist.com/r-guide-longitudinal-lme-lmer
** R code for Cleveland dot plot using ggplot2
[2018-06-05 Mar 18:48]
https://uc-r.github.io/cleveland-dot-plots
** Course on the analysis of discrete data using R
[2018-06-06 Mer 10:28]
https://onlinecourses.science.psu.edu/stat504/
** So nice illustration of ML principles
[2018-06-06 Mer 10:37]
http://www.r2d3.us/visual-intro-to-machine-learning-part-1/
** How to configure Emacs flycheck for ES6
[2018-06-07 Jeu 11:22]
http://codewinds.com/blog/2015-04-02-emacs-flycheck-eslint-jsx.html
** Interesting online book
[2018-06-08 Ven 13:41]
https://www.bookofproofs.org/branches/
** Interesting book or not?
[2018-06-08 Ven 19:24]
http://www.statsref.com/StatsRefSample.pdf
** Nice setup for Pytjon. It should work with Rust too. Looking forward to cquery!
 [2018-06-12 Mar 16:39]
 https://vxlabs.com/2018/06/08/python-language-server-with-emacs-and-lsp-mode/
** Read this for Stata GLMs
 [2018-06-13 Mer 22:00]
 https://stats.idre.ucla.edu/stata/webbooks/logistic/chapter3/lesson-3-logistic-regression-diagnostics/
** Better than Spark? What's the difference? See the xgboost project.
 [2018-06-18 Lun 19:48]
 http://flink.apache.org/
** See how it is going wrt. existing implementation. Also related: https://github.com/danking/racket-ml.
 [2018-06-21 Jeu 09:46]
 https://github.com/mkierzenka/Racket_NumericalMethods
** Good starter kit for git collaboration. See also (more recent): https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/
 [2018-06-22 Ven 11:08]
 https://code.tutsplus.com/tutorials/how-to-collaborate-on-github--net-34267
** Stata histogram with survey weights
 [2018-06-22 Ven 16:45]
 https://stackoverflow.com/questions/32121901/stata-density-distribution-functions-with-survey-data
** NHANES dataset for Stata
 [2018-06-22 Ven 23:30]
 https://www.icpsr.umich.edu/icpsrweb/NACDA/series/39
** Anlysis of NHANES dataset in Stata
 [2018-06-22 Ven 23:32]
 https://stats.idre.ucla.edu/stata/seminars/applied-svy-stata13/
** Nice summary of some Stata commands for test and modeling
 [2018-06-26 Mar 10:14]
 http://nepaldevelopment.pbworks.com/w/page/61335021/STATA%3A%20Quick%20Command%20Reference
** Security and ML in Python @ssi.gouv.fr
 [2018-06-27 Mer 18:44]
 https://github.com/ANSSI-FR/SecuML
** Is it better than cquery?
 [2018-07-04 Mer 21:06]
 https://github.com/MaskRay/ccls
** Useful tips for scientific computing using floats in Racket
 [2018-07-05 Jeu 10:38]
 https://stackoverflow.com/questions/16009143/scientific-notation-conversion-scheme
** Interesting tutorials on numerical methods.
 [2018-07-05 Jeu 13:01]
 https://math.la.asu.edu/~dajones/
** Now that it reaches version 1.0 I should try BeakerX gain
 [2018-07-06 Ven 12:32]
 http://beakerx.com/
** Useful add-ons for Stata twoway
 [2018-07-07 Sam 10:08]
 https://stats.idre.ucla.edu/stata/faq/graph/njc-stata-plots/
** Is this why I get so blurry font rendering with my HP external monitor?
 [2018-07-07 Sam 11:30]
 https://apple.stackexchange.com/questions/299820/font-smoothing-in-high-sierra/300025
** Operating Systems: From 0 to 1
 [2018-07-10 Mar 08:37]
 https://tuhdo.github.io/os01/
** Interesting minimalistic theme and concept (albeit for VS Code)
 [2018-07-13 Ven 20:22]
 https://github.com/tonsky/vscode-theme-alabaster
** Clojure DSL for Apacke Spark
 [2018-07-16 Lun 08:08]
 https://github.com/yieldbot/flambo
** Interesting links on stat libs for Clojure
 [2018-07-16 Lun 08:12]
 https://www.reddit.com/r/Clojure/comments/6kjdrk/is_there_an_actively_developed_stats_library_for/
** Reread this when I will be more proficient using core Clojure
 [2018-07-16 Lun 15:28]
 https://github.com/nathanmarz/specter
** Useful ressource on mathematical statistics
 [2018-07-17 Mar 18:39]
 http://math.usu.edu/symanzik/
** Petit traité de Lisp en français
 [2018-07-19 Jeu 09:33]
 http://dept-info.labri.fr/~strandh/Teaching/Programmation-Symbolique/Common/Book/Dir.html
** Clojure and AWS Lambda
 [2018-07-21 Sam 07:02]
 https://aws.amazon.com/fr/blogs/compute/clojure/
** Getting Started on Heroku with Clojure
 [2018-07-21 Sam 07:02]
 https://devcenter.heroku.com/articles/getting-started-with-clojure
** Interesting approach for managing Git projects
 [2018-07-29 Dim 17:18]
 https://github.com/git-up/GitUp
** I should try this at some point
 [2018-07-29 Dim 18:06]
 https://github.com/deadc0de6/dotdrop
** Base 16 shell color
 [2018-07-29 Dim 18:12]
 https://github.com/chriskempson/base16-shell
** Teach yourself programming in ten years
 [2018-07-30 Lun 21:19]
 http://norvig.com/21-days.html
** Successor of window-purpose
 [2018-10-03 Wed 18:24]
 https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bspacemacs/spacemacs-purpose
** Interesting tool to manage Github repo from the command line
 [2018-10-03 Wed 18:27]
 http://myusuf3.github.io/octogit/
** Meow Hash algorithm; see also https://github.com/bodil/meowhash-rs
 [2018-10-22 Mon 19:29]
 https://mollyrocket.com/meowhash
** Interesting config for org and Hugo
 [2018-10-27 Sat 17:43]
 https://www.shanesveller.com/blog/2018/02/13/blogging-with-org-mode-and-ox-hugo/
** Blot on your local machine
 [2018-11-20 Tue 20:49]
 https://github.com/davidmerfield/Blot
** Interesting cheatsheet for Org babel
 [2018-11-20 Tue 20:59]
 https://necromuralist.github.io/posts/org-babel-cheat-sheet/
** Interesting list of algorithms implemented in different languages
 [2018-11-23 Fri 17:55]
 https://github.com/Thuva4/Algorithms
** Interesting tutorials on Racket
 [2019-01-15 Tue 19:31]
 https://courses.cs.washington.edu/courses/cse341/12au/index.html
** Useful tricks to configure iCloud and Gmail using isync
 [2019-01-25 Fri 10:30]
 https://ict4g.net/adolfo/notes/2014/12/27/EmacsIMAP.html
** Another nice tutorial on setting up mu4e
 [2019-01-25 Fri 11:52]
 http://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and-/
** Nice custom functions for mu4e and org-mode
 [2019-01-29 Tue 08:59]
 https://gitlab.com/ambrevar/dotfiles/blob/master/.emacs.d/lisp/init-mu4e.el
** Biomedical Data Science (R and Bioconductor)
 [2019-02-05 Tue 08:43]
 http://genomicsclass.github.io/book/
** Three algorithms with Python code for Gradient descent. See also http://ruder.io/optimizing-gradient-descent/ and https://jermwatt.github.io/mlrefined/.
 [2019-02-10 Sun 11:35]
 https://www.hackerearth.com/blog/machine-learning/3-types-gradient-descent-algorithms-small-large-data-sets/
** Ninety-Nine Lisp Problems
 [2019-02-10 Sun 14:06]
 https://www.ic.unicamp.br/~meidanis/courses/mc336/2006s2/funcional/L-99_Ninety-Nine_Lisp_Problems.html
** Difference between setq and setf in Common Lisp
 [2019-02-11 Mon 10:57]
 https://stackoverflow.com/questions/869529/difference-between-set-setq-and-setf-in-common-lisp
** Interesting library for math computing
 [2019-02-11 Mon 13:53]
 https://github.com/mfiano/gamebox-math
** Google Calendar With Org-Mode
 [2019-02-12 Tue 20:42]
 http://jameswilliams.be/blog/2016/01/11/Taming-Your-GCal.html
** Lisp and bioinformatics
 [2019-02-13 Wed 13:45]
 https://omicsomics.blogspot.com/2017/09/why-is-lisp-so-rare-in-bioinformatics.html
** Performance and types in Lisp
 [2019-02-13 Wed 19:12]
 https://blog.30dor.com/2014/03/21/performance-and-types-in-lisp/
** Org babel reference card
 [2019-02-13 Wed 19:32]
 https://org-babel.readthedocs.io/en/latest/
** Phylogenetic Network Software
 [2019-02-15 Fri 09:36]
 http://www.fluxus-engineering.com/sharenet.htm
** How to read MD5 hash efficiently in Python 2/3. See also https://stackoverflow.com/a/20014805
 [2019-02-16 Sat 11:02]
 https://stackoverflow.com/questions/1131220/get-md5-hash-of-big-files-in-python/40961519#40961519
** Introduction to ML with Common Lisp
 [2019-02-16 Sat 12:57]
 https://gorkovchanin.wordpress.com/2017/07/21/introduction-to-ml-with-common-lisp/
** BioJulia packages. See also https://julialang.org/blog/2015/10/biojulia-sequence-analysis
 [2019-02-16 Sat 14:07]
 https://biojulia.net/
** What's the most efficient file format for the storage of DNA sequences?
 [2019-02-16 Sat 14:09]
 https://bioinformatics.stackexchange.com/questions/1/whats-the-most-efficient-file-format-for-the-storage-of-dna-sequences
** Check these new estimators and the [[https://github.com/neurospin/pylearn-parsimony][parsimony]] package
 [2019-02-16 Sat 20:47]
 http://neurospin.github.io/pylearn-parsimony/tutorials.html
** Emacs for Travis CI
 [2019-02-17 Sun 09:06]
 https://github.com/flycheck/emacs-travis
** IPython kernel for Racket
 [2019-02-17 Sun 09:15]
 https://github.com/ppaml-op3/iracket
** Set Forklift as the default file manager. See also [[https://johnscullen.com/how-to-make-forklift-3-the-default-file-viewer/][How to make ForkLift 3 the default file viewer]]
 [2019-02-18 Mon 12:11]
 https://apple.stackexchange.com/questions/45809/set-forklift-as-default-file-viewer/45831#45831
** Resources for Population Genetics in R
 [2019-02-19 Tue 10:53]
 https://github.com/emmanuelparadis/popgenInfo
** Phylogenetic trees in Python
 [2019-02-19 Tue 12:20]
 https://github.com/Zsailer/phylogenetics/blob/master/docs/index.rst
** Trees in SQL. See also https://www.postgresql.org/docs/9.0/ltree.html
 [2019-02-19 Tue 12:21]
 https://communities.bmc.com/docs/DOC-9902
** Software for bayesian phylogeny
 [2019-02-20 Wed 07:42]
 http://nbisweden.github.io/MrBayes/download.html
** Galaxy Pasteur
 [2019-02-20 Wed 07:43]
 https://galaxy.pasteur.fr/?form=dnapars
** Tips on using org-journal
 [2019-02-20 Wed 09:11]
 https://bastibe.de/2018-04-02-scheduling-future-todos-in-org-journal.html
** Classification of genome data with n-gram models using Mathematica
 [2019-02-20 Wed 10:51]
 https://mathematicaforprediction.wordpress.com/tag/markov-chains/
** Markov Chains and evolution
 [2019-02-20 Wed 10:56]
 https://math.la.asu.edu/~jtaylor/teaching/Spring2015/APM504/APM504.html
** A Biologist's Guide to Mathematical Modeling with Mathematica applications
 [2019-02-20 Wed 11:14]
 http://www.zoology.ubc.ca/biomath/
** Programming with strings in Mathematica
 [2019-02-20 Wed 12:43]
 https://www.mathematica-journal.com/2013/04/strings/
** Writing fast Mathematica code
 [2019-02-21 Thu 10:28]
 https://blog.wolfram.com/2011/12/07/10-tips-for-writing-fast-mathematica-code/
** Sample matehmatica notebooks for biology
 [2019-02-21 Thu 10:30]
 http://theory.bio.uu.nl/sb/wiskunde/Mathematica/
** Phylogenetic trees in Mathematica
 [2019-02-21 Thu 11:40]
 https://mathematica.stackexchange.com/questions/126496/how-to-work-with-phylogenetic-trees
** Various courses on stochastic processes
 [2019-02-21 Thu 12:51]
 https://math.la.asu.edu/~jtaylor/courses.html
** Functional programming in Mathematica
 [2019-02-23 Sat 08:52]
 https://reference.wolfram.com/language/guide/FunctionalProgramming.html
** How to handle simple and complex rules in Timing App
 [2019-02-23 Sat 10:33]
 https://timingapp.com/help/rules
** Processing and visualization tools for quantitative MRI data using Mathematica
 [2019-02-24 Sun 09:33]
 https://github.com/mfroeling/QMRITools
** Nice posts by Pearly Spencer on Stata
 [2019-02-25 Mon 09:08]
 https://stackoverflow.com/search?q=user%3A8682794+%5Bstata%5D+program
** Internet guide to Stata
 [2019-02-25 Mon 09:37]
 http://wlm.userweb.mwn.de/Stata/
** Tutoriel Perl et DBI
 [2019-02-25 Mon 11:55]
 https://djibril.developpez.com/tutoriels/perl/perl-dbi/
** Tutorial on Flask and MySQL
 [2019-02-25 Mon 12:15]
 https://code.tutsplus.com/tutorials/creating-a-web-app-from-scratch-using-python-flask-and-mysql--cms-22972
** Algorithms for computational biology
 [2019-02-25 Mon 18:03]
 https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-096-algorithms-for-computational-biology-spring-2005/
** PHASE manual including discussion of phylogenetic theory
 [2019-02-25 Mon 18:35]
 http://bioinf.man.ac.uk/resources/phase/manual/node1.html
** Interesting blog
 [2019-02-25 Mon 18:54]
 http://johnhawks.net/
** Finding subsequences in strings
 [2019-02-25 Mon 20:50]
 https://www.geeksforgeeks.org/given-two-strings-find-first-string-subsequence-second/
** Is there an actively developed stats library for Clojure?
 [2019-02-26 Tue 07:57]
 https://www.reddit.com/r/Clojure/comments/6kjdrk/is_there_an_actively_developed_stats_library_for/
** Concatenates FASTA formatted files to one "phyml" (PHYLIP) formatted file
 [2019-02-26 Tue 09:47]
 https://github.com/nylander/catfasta2phyml
** Handling phylogenomic data
 [2019-02-26 Tue 09:53]
 http://odiogosilva.github.io/TriFusion/
** FASTA to sequential PHYLIP format converter
 [2019-02-26 Tue 09:57]
 http://aligner.azurewebsites.net/
** SSE3 support on macOS Macbook
 [2019-02-26 Tue 10:13]
 https://stackoverflow.com/questions/45917280/mac-osx-minumum-support-sse-version
** Elegant operations on matrix rows and columns
 [2019-02-26 Tue 13:01]
 https://mathematica.stackexchange.com/questions/3069/elegant-operations-on-matrix-rows-and-columns
** Useful tips for Mathjax
 [2019-02-26 Tue 20:05]
 https://yutsumura.com/mathjax-in-wordpress/
** Nice tutorial on deploying a Flask app on Heroku
 [2019-02-27 Wed 11:07]
 https://medium.com/the-andela-way/deploying-a-python-flask-app-to-heroku-41250bda27d0
** How to setup a Git mirror to have Travis CI working on Bitbucket
 [2019-02-27 Wed 16:48]
 https://pythonwise.blogspot.com/2012/05/using-travis-ci-with-bitbucket.html
** Travis tutorial
 [2019-02-27 Wed 18:10]
 https://docs.travis-ci.com/user/tutorial/
** How to setup Travis CI with GH pages and Hugo
 [2019-02-27 Wed 20:16]
 https://axdlog.com/2018/using-hugo-and-travis-ci-to-deploy-blog-to-github-pages-automatically/
** Netlify setup
 [2019-02-27 Wed 20:28]
 https://www.netlify.com/docs/cli/
** Heroku and Python/Flask
 [2019-02-28 Thu 09:53]
 https://coderwall.com/p/pstm1w/deploying-a-flask-app-at-heroku
** Codekit: Build websites faster and better
 [2019-02-28 Thu 09:55]
 https://codekitapp.com/index.html
** A template to get your Flask app running on Heroku as fast as possible
 [2019-02-28 Thu 09:56]
 https://github.com/zachwill/flask_heroku
** Making a Flask app using a PostgreSQL database and deploying to Heroku
 [2019-02-28 Thu 10:02]
 http://blog.sahildiwan.com/posts/flask-and-postgresql-app-deployed-on-heroku/
** Postgres guide
 [2019-02-28 Thu 17:38]
 http://postgresguide.com/
** Getting started with Docker on a Mac
 [2019-02-28 Thu 19:38]
 https://docs.docker.com/docker-for-mac/
** Another nice tutorial on Flask
 [2019-03-04 Mon 10:50]
 https://realpython.com/flask-by-example-part-2-postgres-sqlalchemy-and-alembic/
** Another tutorial on Flask + Postgresql
 [2019-03-04 Mon 10:55]
 https://blog.theodo.fr/2017/03/developping-a-flask-web-app-with-a-postresql-database-making-all-the-possible-errors/
** Flask 101
 [2019-03-04 Mon 10:58]
 https://www.blog.pythonlibrary.org/2017/12/12/flask-101-getting-started/
** Difference between pipvenv and virtualenv
 [2019-03-04 Mon 11:25]
 https://stackoverflow.com/questions/41573587/what-is-the-difference-between-venv-pyvenv-pyenv-virtualenv-virtualenvwrappe
** Python + Postgresql tutorials
 [2019-03-04 Mon 16:50]
 http://www.postgresqltutorial.com/postgresql-python/
** Python and alembic
 [2019-03-04 Mon 17:58]
 https://overiq.com/flask-101/database-migrations-with-alembic/
** IMDb data and SQL
 [2019-03-06 Wed 07:43]
 https://www.decisivedata.net/blog/import-data-from-multiple-csv-files-using-bulk-insert
** PostgreSQL and bash Stuff
 [2019-03-06 Wed 10:22]
 https://www.manniwood.com/postgresql_and_bash_stuff/index.html
** Drawing Graphs Directly in Psql
 [2019-03-06 Wed 16:08]
 http://akorotkov.github.io/blog/2016/06/09/psql-graph/
** Turn your PostgreSQL queries into Charts
 [2019-03-07 Thu 08:09]
 https://github.com/dimitri/pgcharts
** Haskell programming from manu.el
 [2019-03-07 Thu 09:44]
 https://github.com/manuel-uberti/haskell-programming
** Modern R with the tidyverse
 [2019-03-07 Thu 10:08]
 https://b-rodrigues.github.io/modern_R/
** How to Build a Machine Learning App from Scratch
 [2019-03-08 Fri 09:24]
 https://camtsmith.com/articles/2017-10/naive-bayes-text-classification
** Netlify vs Heroku
 [2019-03-08 Fri 12:07]
 https://linuxhint.com/netlify_vs_heroku/
** How to Type Common Symbols and Special Characters in Mac OS X
 [2019-03-08 Fri 12:19]
 https://www.chriswrites.com/how-to-type-common-symbols-and-special-characters-in-os-x/
** Yet another Flask tutorial with login and Heroku
 [2019-03-11 Mon 07:49]
 https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-v-user-logins
** Taxonomic trees in SQL
 [2019-03-12 Tue 07:35]
 http://gbif.blogspot.com/2012/06/taxonomic-trees-in-postgresql.html
** Managing local biological databases with the BioSQL module
 [2019-03-12 Tue 07:41]
 https://biopython.org/wiki/BioSQL
** BeautifulSoup: removing tags
 [2019-03-12 Tue 19:10]
 https://kaijento.github.io/2017/03/30/beautifulsoup-removing-tags/
** Skip List vs. Binary Search Tree
 [2019-03-15 Fri 10:10]
 https://stackoverflow.com/questions/256511/skip-list-vs-binary-search-tree
** Org export html options
 [2019-03-16 Sat 09:35]
 https://orgmode.org/manual/Export-settings.html
** Old good Emacs tutor
 [2019-03-18 Mon 11:06]
 https://www.tuteurs.ens.fr/unix/editeurs/emacs.html
** A DNA Sequence Alignment/Map (SAM) library for Common Lisp
 [2019-03-20 Wed 13:27]
 https://github.com/keithj/cl-sam
** Little Book of R for Bioinformatics
 [2019-03-20 Wed 13:33]
 https://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/
** Validated, scalable, community developed variant calling, RNA-seq and small RNA analysis
 [2019-03-20 Wed 13:52]
 https://github.com/bcbio/bcbio-nextgen
** A DNA Sequence Alignment/Map (SAM) library for Clojure
 [2019-03-20 Wed 13:53]
 https://chrovis.github.io/cljam/
** scikit-bio is an open-source, BSD-licensed, Python package providing data structures, algorithms, and educational resources for bioinformatics.
 [2019-03-20 Wed 14:04]
 https://github.com/biocore/scikit-bio
** Machine learning with clojure in 2018
 [2019-03-22 Fri 10:13]
 https://www.reddit.com/r/Clojure/comments/7w5ceh/machine_learning_with_clojure_in_2018/
** Binary search tree in Racket
 [2019-03-22 Fri 10:13]
 https://learningtogetolder.wordpress.com/2013/08/14/creating-a-binary-search-tree-in-racket/
** Cigar encoding
 [2019-03-22 Fri 10:15]
 https://genome.sph.umich.edu/wiki/SAM#What_is_a_CIGAR.3F
** Longest Common Subsequence using Scheme
 [2019-03-22 Fri 10:16]
 https://programmingpraxis.com/2009/06/09/longest-common-subsequence/
** Sequence Manipulation Suite
 [2019-03-22 Fri 10:17]
 https://www.bioinformatics.org/sms2/
** Check Lispy for Python inline evaluation
 [2019-03-22 Fri 11:08]
 https://github.com/abo-abo/lispy/
** ThinkStats in Clojure ([[https://metail.com/technology/think-stats-in-clojure-i/][www]])
 [2019-03-23 Sat 08:44]
 https://github.com/ray1729/thinkstats
** Awk tutorial
 [2019-03-23 Sat 08:45]
 http://www.grymoire.com/Unix/Awk.html
** Essential AWK Commands for Next Generation Sequence Analysis
 [2019-03-25 Mon 12:44]
 http://bioinformatics.cvr.ac.uk/blog/category/awk/
** sed and awk for genomics
 [2019-03-25 Mon 12:45]
 https://genomebio.org/sed-awk/
** Most Commonly used Awk by Bioinformatician
 [2019-03-25 Mon 12:45]
 http://bioinformaticsonline.com/pages/view/2573/most-commonly-used-awk-by-bioinformatician
** Bioinformatics one-liners
 [2019-03-25 Mon 12:46]
 https://github.com/stephenturner/oneliners
** Lecture notes on Complex Systems in Biology
 [2019-03-26 Tue 13:25]
 http://rocs.hu-berlin.de/complexsys2018/lectures/
** Hugo slim theme
 [2019-03-26 Tue 15:03]
 https://github.com/oblitum/hugo-theme-slim
** Zeit now examples
 [2019-03-26 Tue 18:43]
 https://github.com/zeit/now-examples
** How to migrate old networkx code
 [2019-03-26 Tue 18:43]
 https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html
** Krigging
 [2019-03-27 Wed 09:36]
 https://desktop.arcgis.com/fr/arcmap/10.3/tools/3d-analyst-toolbox/how-kriging-works.htm
** Comparing different approaches to evolutionary simulations
 [2019-03-27 Wed 13:57]
 http://slideviewer.herokuapp.com/github/yoavram/ipython-notebooks/blob/master/simulation%20frameworks.ipynb#/
** Interesting courses
 [2019-03-27 Wed 14:20]
 http://www.peterbeerli.com/classes/index.php?title=Main_Page
** Modern Regression Analysis
 [2019-03-28 Thu 11:40]
 http://biostat.mc.vanderbilt.edu/wiki/Main/CourseBios312
** Bayesian Evolutionary Analysis by Sampling Trees
 [2019-03-29 Fri 10:42]
 https://github.com/CompEvol/beast2
** Emacs EShell Parameters
 [2019-03-29 Fri 20:02]
 https://github.com/howardabrams/dot-files/blob/master/emacs-eshell.org
** Remote pbcopy on OS X systems
 [2019-03-31 Sun 08:45]
 https://brettterpstra.com/2014/02/19/remote-pbcopy-on-os-x-systems/
** Remote access for macOS
 [2019-03-31 Sun 08:56]
 https://setapp.com/how-to/how-to-access-your-mac-remotely
** Tutorial on Python package
 [2019-04-01 Mon 08:44]
 https://python-packaging.readthedocs.io/en/latest/
** Virtualbox and postgresql
 [2019-04-01 Mon 15:32]
 http://grismar.net/2011/07/22/virtualbox_running_postgresql/
** Creating a minimal Ubuntu VirtualBox image
 [2019-04-01 Mon 15:38]
 https://matschaffer.com/2011/06/minimal-ubuntu-virtualbox/
** Installing Ubuntu on VirtualBox
 [2019-04-02 Tue 14:55]
 https://henricasanova.github.io/VirtualBoxUbuntuHowTo.html
** Interesting library to find or manage OSS projects
 [2019-04-03 Wed 09:32]
 https://libraries.io/
** Docker vs. Vagrant
 [2019-04-03 Wed 11:24]
 https://www.upguard.com/articles/docker-vs-vagrant
** Zappa -- Serverless Python
 [2019-04-03 Wed 12:54]
 https://github.com/Miserlou/Zappa
** Running Jupyter Lab as a Desktop Application
 [2019-04-03 Wed 21:07]
 http://christopherroach.com/articles/jupyterlab-desktop-app/
** Setting up a local web server on macOS 10.14 “Mojave”
 [2019-04-03 Wed 21:27]
 https://discussions.apple.com/docs/DOC-13841
** CD-HIT sequence identity
 [2019-04-04 Thu 14:39]
 https://www.drive5.com/usearch/manual9/cd_hit_id.html
** Generators and iterables in Python
 [2019-04-08 Mon 09:54]
 https://stackoverflow.com/questions/231767/what-does-the-yield-keyword-do
** ShinyStudio
 [2019-04-08 Mon 13:05]
 https://github.com/dm3ll3n/ShinyStudio
** Fast multi-line FASTA/Q reader in several programming languages
 [2019-04-08 Mon 13:25]
 https://github.com/lh3/readfq
** Interesting R package for descriptive statistics
 [2019-04-09 Tue 13:59]
 https://cran.r-project.org/web/packages/summarytools/index.html
** Analysis of ESS data using R
 [2019-04-09 Tue 14:00]
 http://asdfree.com/european-social-survey-ess.html
** Emacs and Git
 [2019-04-10 Wed 09:45]
 http://alexott.net/en/writings/emacs-vcs/EmacsGit.html
** Netlify dev
 [2019-04-10 Wed 13:07]
 https://www.netlify.com/products/dev/
** Eve (after LightTable)
 [2019-04-10 Wed 13:07]
 http://witheve.com/
** Fuzzy String Comparison
 [2019-04-11 Thu 07:54]
 https://stackoverflow.com/questions/10383044/fuzzy-string-comparison
** Rose for genetic substitution model simulation
 [2019-04-11 Thu 07:54]
 https://popmodels.cancercontrol.cancer.gov/gsr/packages/rose/
** Computational Genomics and Molecular Biology
 [2019-04-15 Mon 11:51]
 https://www.cs.cmu.edu/~durand/03-711/2015/Lectures/
** Simply Scheme: Introducing Computer Science
 [2019-04-15 Mon 13:34]
 https://people.eecs.berkeley.edu/~bh/ss-toc2.html
** A short mathematica course
 [2019-04-15 Mon 13:52]
 http://j-star.org/mathematica_course.html
** Higher level tools for working with CSV data and files in Clojure
 [2019-04-15 Mon 13:54]
 https://github.com/metasoarous/semantic-csv
** SCons for data science and compbio
 [2019-04-15 Mon 14:38]
 https://www.metasoarous.com/scons-for-data-science-and-compbio/
** Gogs -- Un service git auto-hébergé sans-douleur
 [2019-04-16 Tue 10:50]
 https://gogs.io/
** A successful Git branching model
 [2019-04-16 Tue 11:30]
 https://nvie.com/posts/a-successful-git-branching-model/
** How to GitHub: Fork, Branch, Track, Squash and Pull Request
 [2019-04-16 Tue 11:30]
 https://www.gun.io/blog/how-to-github-fork-branch-and-pull-request
** Teaching material: Data analytics and visualization
 [2019-04-17 Wed 09:45]
 https://www.yan-holtz.com/teaching
** Documented Anomaly in Recent Versions of the BLASTN Algorithm and a Complete Reanalysis of Chimpanzee and Human Genome-Wide DNA Similarity Using Nucmer and LASTZ
 [2019-04-17 Wed 09:46]
 https://answersingenesis.org/genetics/dna-similarities/blastn-algorithm-anomaly/
** Interesting approach to learning Racket
 [2019-04-18 Thu 11:05]
 https://artyom.me/learning-racket-1
** Counsel, Ivy and Co.
[2019-05-08 Mer 08:31]
https://truthseekers.io/lessons/how-to-use-ivy-swiper-counsel-in-emacs-for-noobs/
** Markdown and Vim
[2019-05-11 Sam 19:17]
https://jdhao.github.io/2019/01/15/markdown_edit_preview_nvim/
** Brian Ripley's talks
[2019-05-17 Ven 10:35]
http://www.stats.ox.ac.uk/~ripley/talks.html
** Rich book classes in Latex
[2019-05-17 Ven 11:34]
https://tex.stackexchange.com/questions/134215/where-can-i-find-some-rich-book-classes
** Matthias Felleisen homepage
[2019-05-20 Lun 09:59]
https://felleisen.org/matthias/
** Random numbers in Scheme
[2019-05-20 Lun 11:25]
https://stackoverflow.com/questions/14674165/scheme-generate-random
** Programming Praxis Amazon Interview Question, part 2
[2019-05-20 Lun 11:52]
https://thornydev.blogspot.com/2012/12/programming-praxis-amazon-interview.html
** The Scheme Programming Language
[2019-05-20 Lun 19:26]
https://www.scheme.com/tspl4/
** Simulating Brownian motion in R
[2019-05-22 Mer 10:22]
http://phytools.org/eqg/Exercise_4.1/
** Simulated ecosystems
[2019-05-22 Mer 13:19]
https://jobtalle.com/simulated_ecosystems.html
** Interesting repos in Clojure. See also the blog.
[2019-05-24 Ven 13:50]
https://github.com/eigenhombre
** Lisp Notes and Handouts
[2019-05-27 Lun 10:18]
http://www.covingtoninnovations.com/mc/LispNotes/
** Static Generative Art Setup for Clojure
[2019-05-29 Mer 14:02]
http://marvelous-code.com/uncategorized/static-generative-art-setup-for-clojure/
** Immutability with normal JavaScript objects and arrays
[2019-05-31 Ven 13:22]
https://github.com/immerjs/immer
** Typescript and Emacs
[2019-05-31 Ven 18:41]
http://redgreenrepeat.com/2018/05/04/typescript-in-emacs/
** Various string metrics in Lisp
[2019-06-01 Sam 08:31]
https://github.com/cbaggers/mk-string-metrics
** Yet another Emacs configuration
[2019-06-01 Sam 20:23]
https://lthms.xyz/emacs.d
** Nice generative algorithm to draw hyphae
[2019-06-03 Lun 10:04]
https://inconvergent.net/generative/hyphae/
** Dual boot macOS/Ubuntu
[2019-06-04 Mar 11:46]
https://www.lifewire.com/dual-boot-linux-and-mac-os-4125733
** Useful Awk tips and tricks
[2019-06-06 Jeu 10:59]
http://www.grymoire.com/Unix/Awk.html
** Check blog posts and course materials
[2019-06-06 Jeu 10:59]
http://matt.might.net/#teaching
** Processing.js Quick Start
[2019-06-13 Jeu 10:21]
http://processingjs.org/articles/jsQuickStart.html
** A gentle introduction to persistent homology
[2019-06-13 Jeu 10:35]
https://christian.bock.ml/posts/persistent_homology/
** Historical map of Cognitive Science
[2019-06-13 Jeu 10:45]
http://www.riedlanna.com/cognitivesciencemap.html
** Differences between Processing.js and P5.js
[2019-06-13 Jeu 10:56]
https://www.sitepoint.com/processing-js-vs-p5-js-whats-difference/
** Growth Modeling of filamentous fungi
[2019-06-14 Ven 10:22]
http://2018.igem.org/Team:DTU-Denmark/GrowthModelling
** Solutions to Ninety-Nine Lisp Problems
[2019-06-17 Lun 10:34]
http://www.informatimago.com/develop/lisp/l99/
** C programming Solved Programs/Examples with Solutions
[2019-06-17 Lun 15:10]
https://www.includehelp.com/c-programming-examples-solved-c-programs.aspx
** Predator-Prey Modeling in Clojure
[2019-06-19 Mer 15:04]
https://markbastian.github.io/posts-output/2015-04-28-predator-prey/
** Exercises in Clojure with Commentary
[2019-06-19 Mer 15:13]
https://markbastian.github.io/posts-output/2015-05-27-exercises/
** Trees, Quil and Random
[2019-06-20 Jeu 10:36]
http://nbeloglazov.com/2015/05/18/trees-quil-and-random.html
** How to get 64 bit integer in common lisp?
[2019-06-21 Ven 10:10]
https://stackoverflow.com/questions/8674982/how-to-get-64-bit-integer-in-common-lisp
** (gnu) common lisp: features and functions
[2019-06-21 Ven 10:13]
http://www.csci.viu.ca/~wesselsd/courses/csci330/code/lisp/
** Nested for loops in R and Racket
[2019-07-04 Jeu 13:41]
https://www.travishinkelman.com/post/for-loop-r-racket/
** HT Sequence Analysis with R and Bioconductor
[2019-07-05 Ven 14:14]
http://manuals.bioinformatics.ucr.edu/home/ht-seq
** SSC Intro to NGS Bioinformatics Course
[2019-07-05 Ven 14:16]
https://wikis.utexas.edu/display/bioiteam/SSC+Intro+to+NGS+Bioinformatics+Course
** Algorithme de Needleman et Wunsch en Scheme
[2019-07-05 Ven 16:12]
http://www.laurentbloch.org/MySpip3/Algorithme-de-Needleman-et-Wunsch
** C ressources
[2019-07-20 Sat 20:37]
http://people.duke.edu/~tkb13/courses/ncsu-csc230/lecture/
** Racket course
[2019-07-20 Sat 20:59]
https://www.cs.grinnell.edu/~rebelsky/Courses/CSC151/2019S/readings/
** Light alternative to libgen.io
[2019-07-31 Mer 10:25]
https://the-eye.eu/public/Books/
** Sequences in Lisp
[2019-08-09 Fri 09:11]
https://www.slac.stanford.edu/comp/unix/gnu-info/cl_9.html
** Some tips & tricks on Fish and iTerm
[2019-08-16 Ven 08:38]
https://ghaiklor.github.io/iterm-fish-fisher-osx/
** Nord theme for Fish
[2019-08-16 Ven 08:39]
https://github.com/arcticicestudio/nord/issues/102
** TypeScript Language Specification
[2019-08-19 Lun 18:45]
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md
** The Adventures of a Pythonista in Schemeland
[2019-08-19 Lun 18:45]
http://www.phyast.pitt.edu/~micheles/scheme/index.html
** Programming in Haskell - Solutions to slides
[2019-08-21 Wed 07:47]
https://tiefenauer.github.io/blog/programming-in-haskell/
** Using TypeScript with React
[2019-08-22 Thu 10:16]
https://simonknott.de/articles/Using-TypeScript-with-React.html
** Migrating from Python to Racket
[2019-08-22 Thu 16:06]
https://github.com/racket/racket/wiki/Python-to-Racket
** A philosophical difference between Haskell and Lisp
[2019-08-22 Thu 21:00]
https://chrisdone.com/posts/haskell-lisp-philosophy-difference/
** PH525x series - Biomedical Data Science
[2019-08-26 Mon 12:10]
http://genomicsclass.github.io/book/
** Awk one-liner
[2019-08-27 Tue 09:38]
http://tuxgraphics.org/~guido/scripts/awk-one-liner.html
** Emacs and GPG
[2019-08-27 Tue 16:03]
http://prodissues.com/2016/02/emacs-gpg-for-dummies.html
** A productive development environment with Docker on OS X
[2019-08-30 Fri 09:05]
https://www.ybrikman.com/writing/2015/05/19/docker-osx-dev/
** Docker vs. Virtualbox
[2019-08-30 Fri 09:07]
https://www.quora.com/What-is-the-difference-between-containerization-Docker-and-virtualization-VMWare-VirtualBox-Xen
** Lecture notes -- Memory layout in C
[2019-09-06 Fri 10:02]
http://web.eecs.utk.edu/~huangj/cs360/360/notes/Memory/lecture.html
** Sparkling Water provides H2O functionality inside Spark cluster
[2019-09-06 Fri 18:41]
https://github.com/h2oai/sparkling-water
** A collection of algorithms in various langauges
[2019-09-07 Sat 07:56]
http://algorithmexamples.com/
** Git pull vs. git up
[2019-09-09 Mon 09:49]
https://stackoverflow.com/questions/15316601/in-what-cases-could-git-pull-be-harmful/15316602
** Check if there's anything better than that for automagically updating all Git repo
[2019-09-09 Mon 09:55]
https://gist.github.com/douglas/1287372
** RNA-Seq studies of brown rot fungi could lead to new tools for more efficient biofuel production
[2019-09-09 Mon 10:32]
https://www.rna-seqblog.com/rna-seq-studies-of-brown-rot-fungi-could-lead-to-new-tools-for-more-efficient-biofuel-production/
** Python tutorial feat. biopython
[2019-09-09 Mon 14:08]
http://people.duke.edu/~ccc14/pcfb/biopython/BiopythonSequences.html
** Good old friend Wwwblast
[2019-09-10 Tue 13:47]
https://openwetware.org/wiki/Wwwblast
** Clustering RNAseq data using K-means: how many clusters?
[2019-09-10 Tue 16:50]
https://2-bitbio.com/2017/10/clustering-rnaseq-data-using-k-means.html
** PHP and Apache on Mojave
[2019-09-11 Wed 10:10]
https://getgrav.org/blog/macos-mojave-apache-multiple-php-versions
** Online regex tester
[2019-09-11 Wed 15:24]
https://www.regexplanet.com/
** IPython theming
[2019-09-12 Thu 09:26]
https://blog.henryhhammond.com/theming-ipython/
** Hugo + Pygments—How to change highlighting theme?
[2019-09-12 Thu 09:37]
https://stackoverflow.com/questions/38821339/hugo-pygments-how-to-change-highlighting-theme
** IPython customization
[2019-09-12 Thu 09:45]
https://stackoverflow.com/questions/14129278/how-do-i-customize-text-color-in-ipython
** Org-mode Tutorial / Cheat Sheet
[2019-09-16 Mon 14:09]
https://emacsclub.github.io/html/org_tutorial.html
** Org-Mode Is One of the Most Reasonable Markup Languages to Use for Text
[2019-09-16 Mon 17:44]
https://karl-voit.at/2017/09/23/orgmode-as-markup-only/
** Beautiful websites using Emacs's org mode [closed]
[2019-09-16 Mon 17:50]
https://stackoverflow.com/questions/12052013/beautiful-websites-using-emacss-org-mode
** Using org to Blog with Jekyll
[2019-09-17 Tue 14:09]
https://orgmode.org/worg/org-tutorials/org-jekyll.html
** Academic Markdown and Citations
[2019-09-17 Tue 16:19]
https://v4.chriskrycho.com/2015/academic-markdown-and-citations.html
** Removing and purging files from git history
[2019-09-18 Wed 07:47]
https://blog.ostermiller.org/git-remove-from-history
** A curated list of awesome Scheme libraries and resources
[2019-09-18 Wed 15:05]
https://github.com/schemedoc/awesome-scheme
** An alternative exome sequencing pipeline using bowtie2 and samtools
[2019-09-18 Wed 21:40]
http://www.cureffi.org/2012/09/07/an-alternative-exome-sequencing-pipeline-using-bowtie2-and-samtools/
** Nice use of mdfind
[2019-09-22 Sun 20:13]
https://superuser.com/questions/226566/how-do-i-find-a-file-by-filename-in-mac-osx-terminal
** A Practical Introduction to NMF (nonnegative matrix factorization)
[2019-09-23 Mon 10:56]
https://mlexplained.com/2017/12/28/a-practical-introduction-to-nmf-nonnegative-matrix-factorization/
** The Golden Rule of Bioinformatics
[2019-09-23 Mon 14:40]
https://davetang.org/muse/2019/01/23/the-golden-rule-of-bioinformatics/
** Making a heatmap in R with the pheatmap package
[2019-09-23 Mon 14:53]
https://davetang.org/muse/2018/05/15/making-a-heatmap-in-r-with-the-pheatmap-package/
** Tutorial RNA-Seq using R
[2019-09-25 Wed 10:27]
https://www.r-bloggers.com/deseq2-course-work/
** RNA-seq Differential Analysis with R (oldie)
[2019-09-26 Thu 11:49]
https://rstudio-pubs-static.s3.amazonaws.com/218660_7cbe1343ac434dbab59924a80ac2e815.html#ma_plot
** Moving to zsh
[2019-09-28 Sat 17:16]
https://scriptingosx.com/2019/06/moving-to-zsh/
** macOS Setup Guide
[2019-09-30 Mon 13:05]
https://sourabhbajaj.com/mac-setup/
