#+TITLE: Vim 101
#+AUTHOR: chl
#+DATE: August 2020

Former Emacs user here. Trying to uncover the basics of Vim keybindings, especially for selection, movement and action on text objects, when using Doom Emacs (yes, just cheating, I'm still an Emacs guy).

Hereafter, I will consider only three kind of operation: motion, transformations and actions. Motion or movement refers to moving around in the buffer. Transformations are applied to text objects, whether it is a single object (e.g., adjacent word or line) or a visual selection. Finally, actions are all other operations that can operate on a per-buffer basis or on the current selection. I'm not interested in keybindings specific of a particular mode (e.g., VCS, Markdown, Org) although I may record some shortcuts specific to =prog-mode=.

I shall put additional references at a later point. \autocite{neil-2018-moder-vim} In the meantime, here's a nice overview of why Vim may be a good companion for programming stuff, written by Steve Losh: [[https://stevelosh.com/blog/2010/09/coming-home-to-vim/][Coming Home to Vim]].

* Basic stuff

** Motion

Basically, what I usually want to do is: move at the beginning or end of current (physical) line -- in insert mode I use standard Emacs keybinds =C-a= and =C-e=, jump to the previous or next word (but this is generally to yank or delete this word), or to the previous or next blank line (useful in =text-mode= and =prog-mode=). I also like moving between opening and closing brackets or parenthesis. Finally, I find it useful to quickly jump to a specific line number.[fn::Here's a footnote]

|---------+------------------------------------------------------------|
| Keys    | Description                                                |
|---------+------------------------------------------------------------|
| b       | move cursor to previous word                               |
| w       | move cursor to next word                                   |
| 0       | Go to beginning of line                                    |
| $       | Go to end of line                                          |
| gg      | Go to beginning of buffer                                  |
| G       | Go to end of buffer                                        |
| :X      | Go to line number X                                        |
| f<char> | Go to next occurrence of char on line                      |
| F<char> | Go to previous occurrence of char on line                  |
| C-u     | Scroll to previous screen                                  |
| C-d     | Scroll to next screen                                      |
| o       | Toggle between beginning and ending of selection           |
| %       | Toggle between beginning and ending of matching delimiters |
| (       | Jump to beginning of paragraph                             |
| )       | Jump to end of paragraph                                   |
| {       | Jump to next empty line                                    |
| }       | Jump to previous empty line                                |
|---------+------------------------------------------------------------|

\printbibliography
