#+TITLE: Vim 101
#+AUTHOR: chl
#+DATE: August 2020

Former Emacs user here. Trying to uncover the basics of Vim keybindings, especially for selection, movement and action on text objects, when using Doom Emacs (yes, just cheating, I'm still an Emacs guy).

Hereafter, I will consider only three kind of operation: motion, transformations and actions. Motion or movement refers to moving around in the buffer. Transformations are applied to text objects, whether it is a single object (e.g., adjacent word or line) or a visual selection. Finally, actions are all other operations that can operate on a per-buffer basis or on the current selection. I'm not interested in keybindings specific of a particular mode (e.g., VCS, Markdown, Org) although I may record some shortcuts specific to =prog-mode=.

I shall put additional references at a later point. \autocite{neil-2018-moder-vim} In the meantime, here's a nice overview of why Vim may be a good companion for programming stuff, written by Steve Losh: [[https://stevelosh.com/blog/2010/09/coming-home-to-vim/][Coming Home to Vim]].

* Basic stuff

** Motion

Basically, what I usually want to do is: move at the beginning or end of current (physical) line -- in insert mode I use standard Emacs keybinds =C-a= and =C-e=, jump to the previous or next word (but this is generally to yank or delete this word), or to the previous or next blank line (useful in =text-mode= and =prog-mode=). I also like moving between opening and closing brackets or parenthesis. Finally, I find it useful to quickly jump to a specific line number.

So basically, given the following snippet of text, I want to be able to jump quickly to position A, B, C and D, or to select region delimited by either two of these anchors:

#+BEGIN_EXAMPLE
The quick brown fox jumps over the lazy dog.
^   ^                          ^           ^
A   B                          C           D
#+END_EXAMPLE

There are more complex scenarios but I feel like these are the most common jumps: A is the beginning of a sentence (or line), A--B corresponds to moving to the beginning of the next word, A--C is a jump to next word that start with a 't', and D is the end of the sentence (or line), which means that A--D is akin to jumping from the beginning to the end of the sentence.

#+NAME:    tab:motion
#+LABEL:   tab:motion
#+CAPTION: Basic shortcuts for motion in visual mode
|---------+------------------------------------------------------------|
|---------+------------------------------------------------------------|
| Keys    | Description                                                |
|---------+------------------------------------------------------------|
| b       | move cursor to previous word                               |
| w       | move cursor to next word                                   |
| 0       | Go to beginning of line                                    |
| $       | Go to end of line                                          |
| gg      | Go to beginning of buffer                                  |
| G       | Go to end of buffer                                        |
| :X      | Go to line number X                                        |
| f<char> | Go to next occurrence of char on line                      |
| F<char> | Go to previous occurrence of char on line                  |
| C-u     | Scroll to previous screen                                  |
| C-d     | Scroll to next screen                                      |
| o       | Toggle between beginning and ending of selection           |
| %       | Toggle between beginning and ending of matching delimiters |
| (       | Jump to beginning of paragraph                             |
| )       | Jump to end of paragraph                                   |
| {       | Jump to next empty line                                    |
| }       | Jump to previous empty line                                |
|---------+------------------------------------------------------------|
|---------+------------------------------------------------------------|

The shortcuts listed in Table [[tab:motion2]] are specific to Doom Emacs and are usually mapped under the =g= or =z= prefix operator. There are also keybindings specific to =prog-mode= like =gd= or =gD=: they are mapped to the corresponding =xref-find-*= functions unless the [[https://emacs-lsp.github.io/lsp-mode/][lsp]] package is installed in which case they are associated to =lsp-find-*= functions.

#+NAME:    tab:motion2
#+LABEL:   tab:motion2
#+CAPTION: Motion shortcuts in visual mode for Doom Emacs
|------+-----------------------------------|
|------+-----------------------------------|
| Keys | Description                       |
|------+-----------------------------------|
| g;   | Goto last change                  |
| g^   | First non blank character         |
| g0   | Jump to beginning of visual line  |
| gm   | Jump to middle of visual line     |
| g$   | Jump to end of visual line        |
| gd   | Go to definition                  |
| gD   | Go to references                  |
| zz   | Scroll line to center (of screen) |
| zb   | Scroll line to bottom             |
| zt   | Scroll line to top                |
|------+-----------------------------------|
|------+-----------------------------------|


\printbibliography
