* On BSD and MIT licenses

#+FILETAGS: :computing:

Actually there are four BSD licenses:

1. zero-clause BSD: Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted.
2. two-clause BSD:

   #+BEGIN_QUOTE
   Redistribution and use in source and binary forms, with or without modification, are permitted
   provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice, this list of conditions
   and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice, this list of conditions
   and the following disclaimer
   in the documentation and/or other materials provided with the distribution.
   #+END_QUOTE

3. three-clause BSD: two-clause BSD + Neither the name of the [organization] nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
4. four-clause BSD: three-clause BSD + All advertising materials mentioning features or use of this software must display the following acknowledgement: This product includes software developed by the [organization].

On the contrary, the MIT license does not include claure reagrding advertisment like in the BSD 3 license, but it features an attribution clause:

#+BEGIN_QUOTE
Permission is hereby granted, free of charge, to any person obtaining a copy of this software
and associated documentation files (the "Software"), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.
#+END_QUOTE

The closest licenses are probably BSD 2 and MIT, although the MIT license further allows to merge, publish, sublicense or even sell existing work.
